### PR TITLE
feat: Updated to `cortex-debug@1.5.1`

### LINKED ISSUE #246: Update Cortex-Debug to recent version
**Is your feature request related to a problem? Please describe.**
A clear an request related to a problem? Please describe.**
The version of Cortex-Debug in ide code is 0.3.7 the current version is 0.3.12 from feb 2021, the main difference, apart from some bugfixes is added support for STM32Cube debug server.

**Describe the solution you'd like**
Update version from 0.3.7 to 0.3.12

### LINKED ISSUE #1582: Unable to start debugger when watch expressions are configured
### Describe the problem

Arduino IDE has [an integrated debugger for debugging sketches](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-debugger).

One of the features of the debugger is the ability to configure expressions to "watch", which is useful for tracking the value of variables at each point in the program execution.

🐛 If a watch expression is configured, the debugger fails to start.

#### Equipment

Any board of a platform that is configured for use with the debugger (currently only ["**Arduino SAMD (32-bits ARM Cortex-M0+) Boards**" platform](https://github.com/arduino/ArduinoCore-samd) AFAIK).

A CMSIS-DAP compliant or J-Link debug probe. Note that the [Arduino Zero](https://store.arduino.cc/products/arduino-zero) has an on-board debug probe.

#### Steps

1. Set up your board as needed for use with the debugger.
1. Create and save a sketch that contains a variable you can watch:
   ```cpp
   int foo;
   void setup() {}
   void loop() {
     foo++;
   }
   ```
1. If you are using a J-Link, add the `debug_custom.json` file to the sketch:
   https://docs.arduino.cc/tutorials/mkr-wifi-1010/mkr-jlink-setup#debugging-in-arduino-ide-20
1. Enable **Sketch > Optimize for Debugging** in the Arduino IDE menus.
1. Select **Sketch > Upload** from the Arduino IDE menus.
1. Wait for the upload to finish.
1. Click the "**Start Debugging**" button in the IDE toolbar.
1. Wait for the debugger to start.
1. Click the **❯** control next to "**WATCH**" in the "**DEBUG**" view to expand the "**WATCH**" section if it is not already expanded.
1. Click the "**+**" icon ("**Add Expression**") button in the "**WATCH**" section heading.
1. In the "**Edit Watch Expression**" field, type `foo`
1. Click the <kbd>**OK**</kbd> button.
   🙂 The `foo` variable is watched as expected.
1. Click the red square icon ("**Stop**") on the debugger toolbar.
1. Click the green triangle icon ("**Start Debugging**") on the debugger toolbar.

🐛 The debugger does not start. An error notification is shown:

> **Request 4 cancelled on connection close**

It will no longer be possible to start the debugger for that sketch even after restarting the IDE.

The debugger can only be started once more after removing the watch expression.

### Expected behavior

Debugger can be started even if a watch expression is configured.

### Arduino IDE version

2.0.1-snapshot-2b2463b

### Operating system

- Windows
- Linux

### Operating system version

- Windows 10
- Ubuntu 20.04

### Additional context

The bug can be worked around by the following procedure:

1. Hover the mouse pointer over the heading of the "**WATCH**" section in the debugger view. You will now see an icon with an **X** at the right side of the heading:
   image
   Click that icon.
1. Start the debugger.
1. Replace any watch expressions you need.

---

I bisected the introduction of the bug to 112153fb / https://github.com/arduino/arduino-ide/pull/791

---

I see the following log output after attempting to start the debugger under these conditions:

```text
root INFO [hosted-plugin: 14416] Creating local connection: 722ebbc7-f483-4d36-bd66-67c1f636e6ec
root INFO [hosted-plugin: 14416] starting debug adapter session '722ebbc7-f483-4d36-bd66-67c1f636e6ec'
root INFO [hosted-plugin: 14416] Creating plugin connection: 722ebbc7-f483-4d36-bd66-67c1f636e6ec
root ERROR [hosted-plugin: 14416] (node:10684) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Arduino IDE --trace-deprecation ...` to show where the warning was created)
root ERROR [hosted-plugin: 14416] C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9
const s=r(3),n=r(1),o=r(12),i=r(51),a=process.binding("constants"),u=i(),c="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", [... and tens of thousands more characters; longer than GitHub will allow in an issue]
root ERROR [hosted-plugin: 14416] n"[object Number]"===n.call(e)&&e%1==0},o.int=o.integer,o.notANumber=function(e){return!o.num(e)||e!=e},  [... and tens of thousands more characters; longer than GitHub will allow in an issue]


TypeError: Cannot read properties of undefined (reading 'showDevDebugOutput')
    at _.wrapTimeStamp (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:21659)
    at _.handleMsg (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:22029)
    at _.<anonymous> (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:39946)
    at Generator.next (<anonymous>)
    at C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:4272
    at new Promise (<anonymous>)
    at s (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:4017)
    at _.evaluateRequest (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:39565)
    at _.dispatchRequest (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:1:12109)
    at _.handleMessage (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:42356)
root INFO [hosted-plugin: 14416] onDebugAdapterExit session: '722ebbc7-f483-4d36-bd66-67c1f636e6ec'
root ERROR Error on disconnect
root ERROR [hosted-plugin: 14416] Error: ENOENT: no such file or directory, open 'c:\Users\per\Documents\Arduino\sketch_oct26b\.vscode\.cortex-debug.registers.state.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2143:35)
    at t.RegisterTreeProvider._saveState (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\extension.js:214:12938)
    at t.RegisterTreeProvider.debugSessionTerminated (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\extension.js:214:13208)
    at k.debugSessionTerminated (C:\ide 2\tip\149-2b2463b\resources\app\plugins\cortex-debug\extension\dist\extension.js:129:61849)
    at C:\ide 2\tip\149-2b2463b\resources\app\node_modules\@theia\core\lib\common\event.js:103:69
    at CallbackList.invoke (C:\ide 2\tip\149-2b2463b\resources\app\node_modules\@theia\core\lib\common\event.js:109:26)
    at Emitter.fire (C:\ide 2\tip\149-2b2463b\resources\app\node_modules\@theia\core\lib\common\event.js:224:29)
    at DebugExtImpl.$sessionDidDestroy (C:\ide 2\tip\149-2b2463b\resources\app\node_modules\@theia\plugin-ext\lib\plugin\node\debug\debug.js:186:52) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'c:\\Users\\per\\Documents\\Arduino\\sketch_oct26b\\.vscode\\.cortex-debug.registers.state.json'
}
```

The problem still occurs, except without the `ENOENT` error in the logs, after I create `c:\Users\per\Documents\Arduino\sketch_oct26b\.vscode\.cortex-debug.registers.state.json`, which makes me question whether that part of the output is relevant.

Prior to 112153fb, there was similar output:

```text
root INFO [hosted-plugin: 14104] PLUGIN_HOST(14104): PluginManagerExtImpl/loadPlugin(E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\extension)
root INFO [hosted-plugin: 14104] Debug configuration provider has been registered: cortex-debug, trigger: 1
root ERROR [hosted-plugin: 14104] (node:10576) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
root ERROR [hosted-plugin: 14104] (node:10576) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'showDevDebugOutput' of undefined
    at _.wrapTimeStamp (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:21659)
    at _.handleMsg (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:22029)
    at _.<anonymous> (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:39946)
    at Generator.next (<anonymous>)
    at E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:4272
    at new Promise (<anonymous>)
    at s (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:4017)
    at _.evaluateRequest (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:39565)
    at _.dispatchRequest (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:1:12109)
    at _.handleMessage (E:\ide2\tip\1-69ac1f4\resources\app\plugins\cortex-debug\extension\dist\debugadapter.js:9:42356)
root ERROR [hosted-plugin: 14104] (node:10576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---

It may be related to https://github.com/arduino/arduino-ide/issues/412 in that this is a report of the watch expression not working if it was configured before the debugger was started.

---

Originally reported at:

- https://forum.arduino.cc/t/getting-the-debugger-to-work/1020797/1
- https://forum.arduino.cc/t/getting-the-debugger-to-work/1020797/8
- https://forum.arduino.cc/t/arduino-zero-debug-error-with-ide-2-0/1046036/1
- https://forum.arduino.cc/t/arduino-zero-debug-error-with-ide-2-0/1046036/4

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
~**Depends on #1662**~ ✅ 

----

### Motivation
To use a more recent version of the `cortex-debug` VS Code extension. 

### Other information

Closes #246
Closes #1582

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
UPDATE: Fixed by https://github.com/arduino/arduino-ide/pull/1706/commits/7c3f1bf202b903c68f5b8b25e5e8719d901258df

<s>
An "**RTOS**" UI element was added to the menu bar.

There is no indication to the user that this is associated with the debugger. The fact that it is located on the menu bar, yet is not a menu is also unintuitive.

For now, I think the "**Toggle RTOS View**" command alone will be sufficient. If it later emerges that a significant portion of Arduino users want more convenient access to the view, perhaps some consideration can be given to exposing it in the IDE's primary UI in some way.

### To reproduce

1. Start Arduino IDE

🐛 The menu bar contains an "**RTOS**" element:

image

### Arduino IDE version

d3cec4f (tester build for https://github.com/arduino/arduino-ide/commit/71d8482c7ef8f22d26b42bdd3a9c74a9930c06a4

### Operating system

Windows

### Operating system version

10
</s>

**Comment by kittaakos** [comment]
Thanks for reporting it. There is not much IDE2 can do but forcefully disable all the contributions the `cortex-debug` extension adds to VS Code/Theia. Is this what we want?

**Comment by kittaakos** [comment]
> 🐛 The menu bar contains an "**RTOS**" element:

It must be a Windows/Linux issue, as there is no RTOS menu on macOS.

Screen Shot 2022-11-28 at 15 58 24

**Comment by kittaakos** [comment]
> There is no indication to the user that this is associated with the debugger. The fact that it is located on the menu bar, yet is not a menu is also unintuitive.
> 
> For now, I think the "**Toggle RTOS View**" command alone will be sufficient. If it later emerges that a significant portion of Arduino users want more convenient access to the view, perhaps some consideration can be given to exposing it in the IDE's primary UI in some way.

I removed the view. Let me know if you see a malfunction or notice other undesired things in the UI. Thanks!

Notes, I could see the RTOS view on Windows but not on macOS. I guess there is a bug upstream with the [`when`](https://code.visualstudio.com/api/references/when-clause-contexts) context evaluation, and that's why the view and menu are visible on Windows but not on macOS. This requires further investigation in Theia.

**Review by per1234 — APPROVED** [review]
I tested it on Windows and Linux and everything is working perfectly.

I verified it fixes https://github.com/arduino/arduino-ide/issues/1582

Thanks Akos!

---

I do want to share some observations:

## Required change to config for J-Link users

On Windows, when using a J-Link debug probe, if I set the `serverpath` field in `debug_custom.json` to point to `JLinkGDBServer`, starting the debugger fails with the notification:

> Failed to launch undefined GDB Server: Timeout.

If I change the configuration to point to `JLinkGDBServerCL` instead, it works fine.

The reasons I was previously using `JLinkGDBServer`:

- It is specified in [Arduino's official tutorial](https://docs.arduino.cc/tutorials/mkr-wifi-1010/mkr-jlink-setup#debugging-in-arduino-ide-20)
- The same executable name can be used on Linux as well (astonishingly, `JLinkGDBServer` is actually a symlink to `JLinkGDBServerCLExe` on Linux, not `JLinkGDBServerExe` as you would expect)

## Creation of files in sketch folder

I don't see this as really a problem, but I thought it was worth mentioning since previously no files were added.

---

If I do the following, a `.vscode/.cortex-debug.registers.state.json` is added to the sketch:

1. Start debugger.
1. Click "**Reset device**" on the debugger toolbar.
1. Click the "Stop" icon on the the debugger toolbar.

---

If I do the following, a `.theia/settings.json` is added to the sketch:

1. Start debugger.
1. Expand the "**CORTEX REGISTERS**" section of the DEBUG view.
1. Hover the mouse pointer over the "**CORTEX REGISTERS**" section toolbar.
1. Click the **0x** icon.

---

**Review by ubidefeo — APPROVED** [review]
I like how the new debugger is behaving.
Skips the stop at entry point, no jumpToMain required anymore (deprecated), stops at first user breakpoint.
Also the variables in watch are updated correctly and in general seems to work well with JLink

LGTM

**Pull request merged**
