### PR TITLE
Serial Monitor autoscroll only makes bottom line partially visible #972

### PR DESCRIPTION
**Pull request by dwightfowler-cd**
### Motivation
A fix for Issue #972

### Change description
Fixed margin of `<pre></pre>` tag used to display each line of text

### Other information
N/A

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by eried** [comment]
Please merge this. 

image

**Comment by dwightfowler-cd** [comment]
Had a chance to sleep on it (literally), and I think modifying the `<pre>` style's margin setting in monitor.css is a much cleaner solution.

**Review by AlbyIanna — APPROVED** [review]
It works for me! Thank you so much for your contribution @dwightfowler-cd 🤗

**Comment by kapyaar** [comment]
Is this fix as simple as updating the css file ? I updated the file on my machine, and restarted the IDE, but the issue still remains. Is there a recompile of some sort required?

**Comment by per1234** [comment]
Hi @kapyaar. The fix is incorporated in the nightly build of the Arduino IDE. If you need the fix then please use the nightly build until the next release of Arduino IDE is made.

The download links for the nightly build are listed here:

https://www.arduino.cc/en/software/#nightly-builds

**Comment by kapyaar** [comment]
@per1234 Gotcha, Installed and working great! such a relieve to see that last line without scrolling.Thanks!

**Comment by el-samiyel** [comment]
> This was solved in 2.0.1 but back again in 2.0.2.
> 
> Not sure if its only limited to when the data present within the serial monitor requires the user to use the scroll bar to scroll right (it seems as if the scroll bar is covering up the last row of text).

Here is a snapshot:

sm

**Comment by per1234** [comment]
Hi @el-samiyel. We are tracking this bug in a dedicated issue: https://github.com/arduino/arduino-ide/issues/1602

**Pull request merged**
