### PR TITLE
feat: moved login entry point to the side-bar

### LINKED ISSUE #1877: Move Cloud "Login entry point" to the sidebar of IDE2
### Describe the request

We hope to introduce and promote Arduino Cloud to as many IDE2 users as possible. We would therefore like to make the integrated cloud login in IDE2 more visible.

#### Outcome

A user avatar together with a popover menu should be added to the "first level of the interface", in the sidebar. The popover menu should contain Arduino cloud related actions, namely Sign in/out and links to the cloud platform.

The existing avatar should be removed, and the "Cloud account state element" (at the bottom of the cloud sketchbook list) should be augmented as per design spec. 

### Additional context
Figma links here

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Moved the Arduino Cloud login from the tree to the sidebar.

### Change description

New login location:

https://user-images.githubusercontent.com/1405703/218430756-cf160982-f5e3-489d-b90c-890c5e0d9237.mp4

### Other information

Closes #1877

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
@91volt, I have noticed the followings:
 - Use `Learn More` instead of `Learn more` in the UI if IDE2 wants to follow to command label naming convention.
 - Use `Sign in to Arduino Cloud` instead of `Sign in with Arduino Cloud`.
What do you think?

**Comment by kittaakos** [comment]
@91volt, I also need instructions on where the `Go to Profile` leads. Thank you!

**Review by 91volt — APPROVED** [review]
@kittaakos lgtm
- My take is that the writing rules needs to be better defined, for now is ok leaving it as implemented
- Fine with me "Sign to Arduino Cloud"
- The Cloud Sketchbook doesn't provide features to handle multiple accounts for now, considering that is ok redirecting to the generic id.arduino.cc when the user click on "Go to profile".

**Comment by kittaakos** [comment]
> * My take is that the writing rules needs to be better defined, for now is ok leaving it as implemented

Can you please explain what you mean? Thanks!

**Comment by 91volt** [comment]
> Can you please explain what you mean? Thanks!

I haven't found any Arduino guidelines on label conventions, it is a topic that needs to be addressed with other teams.
Looking into other labelling conventions it looks like all the other internal words should begins with lowercase. 
So my take is to leave it as you implemented it right now, since there are no clear rules right now.

**Pull request merged**
