### PR TITLE
Register custom themes after the monaco theme init

### LINKED ISSUE #1225: Impossible to see the protocol of the connected board with the dark theme
### Describe the problem

When I have the dark theme active, the protocol (USB) is invisible. It's black on a dark theme.

### To reproduce

 - Open IDE2,
 - Select a `dark` theme,
 - Connect a board,
 - Click on the board selector dropdown.

Screen Shot 2022-07-19 at 16 30 22
Screen Shot 2022-07-19 at 16 30 31

### Expected behavior

I can see what's on the UI.

### Arduino IDE version

7680194feb4294cca72fd820617113d316d579b3

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
If the Arduino custom theme registration happens before the restoration of the existing monaco themes, then any custom theme changes will be ignored.

- Fixes #1225 

### Change description
We need to add a patch introduces a static deferred promise in the monaco-theming service that will be resolved when the restoration is ready.

After upgrading to Theia 1.27.0, this patch should be superflous.

### Other information
The credit for this solution goes to @kittaakos 

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
Please update from the `main`. Thank you!

The changes should contain the app config provider customization. See [here](https://github.com/arduino/arduino-ide/commit/f22be3c58733914e00b7e7862f46720cd7279ec4#diff-a6870b5a4e568e15e82691311605f730496bdc219a03dadb7867ff11c136598d). The content of the `electron-app/patch/frontend/index.js` and `electron/build/patch/frontend/index.js` modules must be the same.

**Review by kittaakos — CHANGES_REQUESTED** [review]
The patched `index.js` modules are not identical.

**Review by kittaakos — APPROVED** [review]
Thank you!

**Review by davegarthsimpson — APPROVED** [review]
LGTM

**Pull request merged**
