### PR TITLE
#1055 Install the `Arduino_BuiltIn` to built-in location

### LINKED ISSUE #1055: Use dedicated location for "built-in" libraries
### Describe the request

Use a dedicated location for the "built-in" library installations, with a lower location priority than [platform bundled libraries](https://arduino.github.io/arduino-cli/latest/platform-specification/#platform-bundled-libraries).

🙂 Library dependency resolution will match the behavior of Arduino IDE 1.x

### Describe the current behavior

In order to allow users to get started with Arduino with the minimum amount of complexity, the Arduino IDE 1.x installation comes with [a collection](https://github.com/arduino/Arduino/blob/1.8.19/build/build.xml#L254-L274) of fundamental Arduino libraries (e.g., [Keyboard](https://github.com/arduino-libraries/Keyboard), [Mouse](https://github.com/arduino-libraries/Mouse), [Servo](https://github.com/arduino-libraries/Servo)) pre-installed. Even experienced users now expect these libraries to be available by default, and many tutorials (both official and 3rd party) have been written based on that assumption. So it is important that Arduino IDE 2.x also provide these libraries.

In order to simplify the Arduino IDE packaging process and ensure users are provided with the newest available, the Arduino Library Manager infrastructure is currently used to install the libraries the first time the Arduino IDE is started (https://github.com/arduino/arduino-ide/pull/663).

Library Manager installs these libraries to the sketchbook folder. Libraries at this location have a higher ["location priority"](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#location-priority) than they did when bundled with the Arduino IDE installation.

🙁 This priority increase can cause the "built-in" library to now be selected by the Arduino sketch build process in a case where a platform bundled library would have been selected when using Arduino IDE 1.x.

### Arduino IDE version

2.0.0-rc7

### Operating system

All

### Operating system version

N/A

### Additional context

This would also provide an alternative solution to https://github.com/arduino/arduino-ide/issues/798

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Use a dedicated install location for the `Arduino_BuiltIn` lib on the first IDE2 start.

### Change description
From now on, the built-in lib will be installed into the `built-in` location of the CLI.

Closes #1055.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
UPDATE: fixed by https://github.com/arduino/arduino-cli/pull/1817/commits/fb57a52211d7ecb5f0a8dd4bdb045c74b95d3363

<s>

### Describe the problem

"built-in" libraries installation fails.

### To reproduce

1. Select **File > Quit** from the Arduino IDE menus if it is running.
1. Delete the "User Data Folder" to adequately simulate a fresh install.
   - **Windows**:
     ```
     C:\Users\<user name>\AppData\Roaming\arduino-ide
     ```
   - **Linux**:
     ```
     ~/.config/arduino-ide
     ```
   - **macOS**:
     ```
     ~/Library/Application Support/arduino-ide
     ```
1. Start the Arduino IDE

🐛 The "built-in" libraries installation fails:

```text
Failed to install library: Arduino_BuiltIn:1.0.0.
Error: 2 UNKNOWN: Builtin libraries directory not set
```

### Expected behavior

Arduino IDE automatically configures Arduino CLI for the built-in libraries installation.

### Arduino IDE version

2.0.0-rc9.2.snapshot-8bb5c61 (tester build for https://github.com/arduino/arduino-ide/pull/1370/commits/092ca2dceab4b6980fee9c59757c9e7d48d1f935)

### Operating system

Windows

### Operating system version

10

### Additional context

The required `directories.builtin.libraries` configuration key is not present in `~/.arduinoIDE/arduino-cli.yaml`.

https://github.com/cmaglie/arduino-cli/blob/byebye_bundles/docs/configuration.md#configuration-keys
</s>

**Review by davegarthsimpson — APPROVED** [review]
LGTM code-wise

**Review by per1234 — APPROVED** [review]
It is working perfectly now.

I verified that this change will align the behavior of the Arduino IDE 2.x "built-in" libraries with that of Arduino IDE 1.x, where they will have a lower "location priority" than platform bundled libraries.

Thanks Akos!

**Comment by kittaakos** [comment]
Thank you for the review.

On-hold until https://github.com/arduino/arduino-cli/pull/1817 is merged.

**Pull request merged**
