### PR TITLE
#1544 Changed the daemon output from `json` to `text`

### LINKED ISSUE #1544: Start the CLI daemon without the `--log-format json`
### Describe the request

The daemon logging is essential in IDE2, but the JSON format adds an unnecessary computation; at least the JSON encoding phase is there. If this means only milliseconds of improvement, it will eventually add up.

Consider starting the daemon without the JSON log format.

```diff
diff --git a/arduino-ide-extension/src/node/arduino-daemon-impl.ts b/arduino-ide-extension/src/node/arduino-daemon-impl.ts
index f859985e..4a3ad882 100644
--- a/arduino-ide-extension/src/node/arduino-daemon-impl.ts
+++ b/arduino-ide-extension/src/node/arduino-daemon-impl.ts
@@ -162,8 +162,6 @@ export class ArduinoDaemonImpl
       '--config-file',
       `"${cliConfigPath}"`,
       '-v',
-      '--log-format',
-      'json',
     ];
     if (debug) {
       args.push('--debug');
```

With the proposed changes 👆, the daemon log output would be this:

```
time="2022-10-07T11:27:08+02:00" level=debug msg="Checking previous results for /Users/a.kitta/Library/Arduino15/packages/arduino/hardware/avr/1.8.5/cores/arduino/HardwareSerial1.cpp (result = /private/var/folders/z1/xkw1yh5n7rz4n8djprp1mdn80000gn/T/arduino-language-server2174793569/core/HardwareSerial1.cpp.o, dep = /private/var/folders/z1/xkw1yh5n7rz4n8djprp1mdn80000gn/T/arduino-language-server2174793569/core/HardwareSerial1.cpp.d)"
```

instead of this:
```
{"level":"debug","msg":"Checking previous results for /Users/a.kitta/Library/Arduino15/packages/arduino/hardware/avr/1.8.5/cores/arduino/HardwareSerial1.cpp (result = /private/var/folders/z1/xkw1yh5n7rz4n8djprp1mdn80000gn/T/arduino-language-server1238442199/core/HardwareSerial1.cpp.o, dep = /private/var/folders/z1/xkw1yh5n7rz4n8djprp1mdn80000gn/T/arduino-language-server1238442199/core/HardwareSerial1.cpp.d)","time":"2022-10-07T11:47:48+02:00"}
```

I believe both log formats are equally OK to consume, but the non-JSON one is cheaper.

### Describe the current behavior

See the request description.

### Arduino IDE version

1e269ac

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

To avoid encoding text to JSON on the CLI side.

### Change description

Dropped the `--log-format json` options from the daemon spawn args.

### Other information

Closes #1544

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by nmzaheer** [comment]
Should the code in the test file needs to be modified? It still allows `json` as `logFormat`.

https://github.com/arduino/arduino-ide/blob/a36524e02ab5fbc2ef333ff67a047dfe5718b306/arduino-ide-extension/src/test/node/arduino-daemon-impl.test.ts#L27-L41

**Review by AlbyIanna — APPROVED** [review]
Looking good!

The output is also more readable IMO
from: 
```
daemon INFO {"level":"info","msg":"Required tool","time":"2022-10-21T10:31:19+02:00","tool":{"ToolName":"arduinoOTA","ToolVersion":"1.2.1","ToolPackager":"arduino"}}
{"level":"info","msg":"Required tool","time":"2022-10-21T10:31:19+02:00","tool":{"ToolName":"arm-none-eabi-gcc","ToolVersion":"7-2017q4","ToolPackager":"arduino"}}
{"level":"info","msg":"Required tool","time":"2022-10-21T10:31:19+02:00","tool":{"ToolName":"bossac","ToolVersion":"1.7.0-arduino3","ToolPackager":"arduino"}}
{"level":"info","msg":"Required tool","time":"2022-10-21T10:31:19+02:00","tool":{"ToolName":"openocd","ToolVersion":"0.10.0-arduino7","ToolPackager":"arduino"}}
```

to: 
```
daemon INFO INFO[0009] Searching tools required for board arduino:samd:mkrwifi1010 
INFO[0009] Required tool                                 tool="arduino:CMSIS@4.5.0"
INFO[0009] Required tool                                 tool="arduino:CMSIS-Atmel@1.2.0"
INFO[0009] Required tool                                 tool="arduino:arduinoOTA@1.2.1"
INFO[0009] Required tool                                 tool="arduino:arm-none-eabi-gcc@7-2017q4"
INFO[0009] Required tool                                 tool="arduino:bossac@1.7.0-arduino3"
INFO[0009] Required tool                                 tool="arduino:openocd@0.10.0-arduino7"
```

--- 
About the comment from [nmzaheer](https://github.com/nmzaheer): yes we should probably remove that flag from the test file too – nice catch, thank you for taking the time to look into the code!
Tests aren't failing anyway, so I won't request changes (in case @kittaakos you left that flag there on purpose for some reason)

**Comment by kittaakos** [comment]
Do you want me to remove test?

**Comment by kittaakos** [comment]
OK. I will create a follow-up to clean up the `text|json` tests. There are multiple remarks:
 - initially, the CLI did not print out the daemon port, so it had to work with both `json` and `text`. That's why we had tests.
 - currently, it does not matter whether `text` or `json` is given after the `--log-format` because the address format is dictated by the `daemon --format jsonmini|text|json` flags.

**Comment by kittaakos** [comment]
Follow-up: https://github.com/arduino/arduino-ide/issues/1576

I am proceeding with the merge.

**Pull request merged**
