### PR TITLE
Improve the UX of the Arduino language server

### LINKED ISSUE #1062: Investigate event listeners when zooming in/out with settings json editor open
### Describe the problem

I am seeing warnings related to the increasing number of event listeners. I could reproduce it with RC7.

### To reproduce

 - Open Settings JSON,
 - Zoom in/out ~200 times

```
init (editor-manager.ts:61)
_postConstruct (instantiation.ts:40)
resolveInstance (instantiation.ts:68)
(anonymous) (resolver.ts:102)
_injectProperties (instantiation.ts:19)
resolveInstance (instantiation.ts:63)
(anonymous) (resolver.ts:102)
resolve (resolver.ts:140)
(anonymous) (container.ts:382)
__webpack_modules__.../node_modules/inversify/lib/container/container.js.Container._get (container.ts:354)
__webpack_modules__.../node_modules/inversify/lib/container/container.js.Container.get (container.ts:246)
(anonymous) (preference-transaction-manager.ts:279)
doSetPreference (abstract-resource-preference-provider.ts:118)
setPreference (abstract-resource-preference-provider.ts:112)
setWithConfigName (user-configs-preference-provider.ts:101)
setPreference (user-configs-preference-provider.ts:109)
set (preference-service.ts:420)
savePreference (settings.ts:249)
save (settings.ts:281)
await in save (async)
execute (edit-contributions.ts:65)
await in execute (async)
executeCommand (command.ts:336)
await in executeCommand (async)
executeKeyBinding (keybinding.ts:478)
run (keybinding.ts:568)
(anonymous) (frontend-application.ts:239)
```

```
root WARN Possible Emitter memory leak detected. 264 listeners added. Use event.maxListeners to increase the limit (175). MOST frequent listener (89):
e.log @ logger-protocol.ts:110
(anonymous) @ logger-frontend-module.ts:41
(anonymous) @ logger.ts:312
(anonymous) @ logger.ts:304
Promise.then (async)
log @ logger.ts:299
i @ logger.ts:45
checkMaxListeners @ event.ts:248
_event._event.Object.assign.maxListeners @ event.ts:190
init @ editor-manager.ts:61
(anonymous) @ instantiation.ts:40
t.resolveInstance @ instantiation.ts:68
(anonymous) @ resolver.ts:102
t.length.a @ instantiation.ts:19
t.resolveInstance @ instantiation.ts:63
(anonymous) @ resolver.ts:102
t.resolve @ resolver.ts:140
(anonymous) @ container.ts:382
e._get @ container.ts:354
e.get @ container.ts:246
(anonymous) @ preference-transaction-manager.ts:279
doSetPreference @ abstract-resource-preference-provider.ts:118
setPreference @ abstract-resource-preference-provider.ts:112
s @ user-configs-preference-provider.ts:101
setPreference @ user-configs-preference-provider.ts:109
set @ preference-service.ts:420
savePreference @ settings.ts:249
save @ settings.ts:287
async function (async)
save @ settings.ts:254
execute @ edit-contributions.ts:77
async function (async)
execute @ edit-contributions.ts:70
executeCommand @ command.ts:336
async function (async)
executeCommand @ command.ts:335
executeKeyBinding @ keybinding.ts:478
run @ keybinding.ts:568
(anonymous) @ frontend-application.ts:239
logger-protocol.ts:110 root WARN     at b._event._event.Object.assign.maxListeners [as onDidChangeCurrentWidget] (file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:2310677)
    at s.init (file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:2747135)
    at file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:8415749
    at Object.t.resolveInstance (file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:8415821)
    at file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:8417509
    at Array.map (<anonymous>)
    at t.length.a (file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:8415476)
    at Object.t.resolveInstance (file:///Applications/Arduino%20IDE.app/Contents/Resources/app/lib/bundle.js:2:8415568)
```

### Expected behavior

Event listeners do not leak.

### Arduino IDE version

rc7

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1191: SaveAs hangs with empty window rotating blue...
### Describe the problem

I was editing one of my throw away sketch (xxx, yyy, zzz) in this case abc.
I decided I wanted to save this one:

So I went to File->SaveAs
It brought up the save as dialog.  Although I thought sort of a random starting directory...

I browsed to where I wanted it: <Sketch folder>/Teensy Tests
And then entered new name: t4_eeprom_test_stress.ino
The dialog went away, it looked like it closed the: abc sketch window
And opened up a new window: 

Which has been hung in the state:
image

Note: I did/do have another sketch open in another window:
image

In this case it does look like it did do the save:
image

### To reproduce

Steps mentioned above

### Expected behavior

I expected it to simply change the title of the open window to the new name.

Alternatively: at least finish opening the window 

### Arduino IDE version

Nightly 0713

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

I am not sure this might be a duplicate or related to a few others.

Like #1111 
Or #1119 

But just in case

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1244: Opening new file is quarter-screen
### Describe the problem

image

### To reproduce

open the ide
file -> open recent -> filename
let the file open while small, don't fullscreen while loading.
after just done loading or at the very end of loading, fullscreen.

the screen will be stuck until you close and reopen, unless you fullscreen while loading or adjust size and reset to fullscreen

### Expected behavior

follow the set window size and fully fill.

### Arduino IDE version

2.0.0-rc9

### Operating system

Windows

### Operating system version

10

### Additional context

if you fullscreen while loading or give more then 10ish seconds(for me), then it will work normally. 

I couldn't find a bug report similar to this, sorry if it a duplicate! 
I am an extremely novice programmer, and I love arduino! Its so much fun, I love learning everything. You guys are loved and amazing and are truly saving me from complete boredom while letting me explore and create. Thank you! 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

The LS is still slow according to users.

### Change description

 - Debounced the connectivity status update.
 - Silent the output channel for the Arduino LS.
 - Delay the problem markers update with 500ms.
 - Do not update the status bar on every `keypress` event.
 - Debounced the tab-bar toolbar updates when typing in editor.
 - Fixed electron menu contribution binding.
 - Aligned the editor widget factory's API to Theia.
 - Set the zoom level when the app is ready (Closes https://github.com/arduino/arduino-ide/issues/1244)
 - Fixed event listener leak (Closes https://github.com/arduino/arduino-ide/issues/1062)

### Other information

Closes #1244
Closes #1062
Closes #1191

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
@per1234 and @ubidefeo,

I am marking this PR ready for review, but I will also verify it locally. This PR took so long. I had some issues with #1263, but it turned out to be a board-specific problem. 

Please note that there is a significant behavior change besides some speedup here and there: the problem decorators arrive in the editor 500ms after finishing the typing. So please expect some latency. Maybe "never arriving decorators" until the next `keypress` event. 😬 I am curious what you think about it. Based on my profiling results, the tweaks should help the frontend.

I do not know if the proposed changes solve the indexing/building performance issue (#714). I could not reproduce it on my Windows env, but all profiling and adjustments were implemented and verified on that machine. So I hope this will improve the overall LS experience in IDE2. 

Please help with testing the review so we can involve the users as soon as possible. Thank you!

**Comment by davegarthsimpson** [comment]
@kittaakos

> Maybe "never arriving decorators" until the next keypress event

Why might they never arrive?

**Comment by kittaakos** [comment]
> Why might they never arrive until next keypress?

Timing.

**Review by davegarthsimpson — APPROVED** [review]
code-wise good for me, great work!

**Review by per1234 — APPROVED** [review]
This provides a very significant performance improvement.

Even though I don't experience the extraordinary resource usage to the level of impact and duration reported at https://github.com/arduino/arduino-ide/issues/714, if I type many characters very quickly (beyond what would be expected for real world usage) when using the latest build from the `main` branch (2.0.0-rc9-snapshot-55927ac), I do see a significant spike in CPU and memory usage of the Arduino IDE process with the `--type=renderer` flag, which persists for longer than expected (~30 seconds) before subsiding to the normal base resource usage levels.

When using the build from this PR, I do not see this significant and tenacious increase in the resource consumption in that process under the samd conditions.

The slightly increased "squiggle latency" does not bother me at all.

Thanks Akos!

**Pull request merged**
