### PR TITLE
#53 Refresh menus when opening example/recent fails.

### LINKED ISSUE #53: Attempt to open deleted sketch from Sketchbook or Examples menus fails silently
Originally posted by @tigoe [here](https://github.com/arduino/arduino-pro-ide/issues/425#issuecomment-785264886):

> Also worth notuing that the Examples menu fails to scan the libraries for examples, as the IDE 1.8.x does. See @ubidefeo 's screenshots to see it.

Context from [here](https://github.com/arduino/arduino-pro-ide/issues/425#issue-804001845):

**Screenshots**
Screenshot 2021-02-08 at 22 51 52
Screenshot 2021-02-08 at 22 55 44

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

IDE2 must notify the user about missing/invalid sketches and update the menus when opening the sketch has failed. This is the expected behavior when opening from `File` > `Open Recent`, `File` > `Sketchbook`, and `File` > `Examples`.

### Other information

Closes #53

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by AlbyIanna — APPROVED** [review]
LGTM 🚀

**Comment by kittaakos** [comment]
I have rebased the PR from the `main`. Please review it. Thank you!

**Comment by AlbyIanna** [comment]
Still working for me ✅

**Review by per1234 — CHANGES_REQUESTED** [review]
UPDATE: resolved by https://github.com/arduino/arduino-ide/compare/c8388a78582727a0bf0b869c097714aad1fd8eca..bc85ea62d6e7b6cc80ffbe78a98f898d76ce8a76

<s>

### Describe the problem

**File > New** has no effect.

### To reproduce

1. Select **File > New** from the Arduino IDE menus.

🐛 Nothing at all happens.

### Expected behavior

A new sketch opens in an additional Arduino IDE window after selecting **File > New**

### Arduino IDE version

2.0.1-snapshot-0359e42 (tester build for 0359e42)

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

The problem does not occur when using the latest build from the `main` branch (2.0.1-snapshot-96cf09d)

</s>

**Review by per1234 — CHANGES_REQUESTED** [review]
### Describe the problem

IDE fails to start if no sketch was opened previously.

### To reproduce

1. Select **File > Quit** from the Arduino IDE menus if it is running.
1. Rename or delete (:warning: cautiously) the following folders to simulate the environment of a first run:
   - **Windows**:
     ```text
     C:\Users\<username>\.arduinoIDE
     ```
     ```text
     C:\Users\<user name>\AppData\Roaming\arduino-ide
     ```
   - Linux:
     ```text
     ~/.arduinoIDE
     ```
     ```text
     ~/.config/arduino-ide
     ```
   - macOS:
     ```text
     ~/.arduinoIDE
     ```
     ```text
     ~/Library/Application Support/arduino-ide
     ```
1. Start the build of the Arduino IDE for this PR.
   🐛 The IDE hangs forever at the startup animation.
1. Close the Arduino IDE window.
1. Start a previous version (e.g., 2.0.0) of the Arduino IDE 2.x.
1. Select **File > Save As...** from the Arduino IDE menus.
   **ⓘ** This is done to cause a previously open sketch to be recorded for restoration the next time the IDE is opened. You could do the same by opening any previously saved sketch.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start the build of the Arduino IDE for this PR.
   🙂 The IDE startup finishes.

### Expected behavior

Arduino IDE starts even when there is no previously opened sketch.

### Arduino IDE version

2.0.1-snapshot-0359e42 (tester build for 0359e42)

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

The problem does not occur when using the latest build from the `main` branch (2.0.1-snapshot-96cf09d)

**Comment by kittaakos** [comment]
Thank you for the review, Per. I have fixed the bug with the new sketch creation; it should solve both issues you had during the verification.

**Comment by kittaakos** [comment]
> * Start the build of the Arduino IDE for this PR.
> * Select **File > Save As...** from the Arduino IDE menus.

After wiping the config folder and starting the IDE2, would you expect to see `File` > `Open Recent` > `Foo`, assuming that the `Foo` sketch was the last IDE2 restored? Thank you!

**Comment by per1234** [comment]
>would you expect to see File > Open Recent > Foo, assuming that the Foo sketch was the last IDE2 restored?

No, but I also wouldn't be surprised to see that, so either way is fine. I only expect that any sketches I open after that to be added to the menu.

**Comment by kittaakos** [comment]
> I also wouldn't be surprised to see that, so either way is fine

Thank you!

IDE2 will show it. Steps to reproduce:
 - Open IDE2, create a sketch, and save it to Sketchbook, `File` > `Quit` the app,
 - Wipe `~/.arduinoIDE/recent-sketches.json` (or rename it),
 - Start IDE2. If IDE2 could restore a non-temp sketch, the `File` > `Open Recent` should contain the corresponding submenu item.

I fixed another use case. It wasn't working. Steps:
 - Open IDE2, open 3-4 valid sketches from the Sketchbook, `File` > `Quit` the app,
 - Wipe `~/.arduinoIDE/recent-sketches.json` (or rename it),
 - Start IDE2. IDE2 should restore all previously opened sketches. Go to `File` > `Quit` > all opened sketches must have a corresponding submenu item.

Thank you so much for doing the PR review, again and again, Per. All issues you have noticed during the verification should be fixed now.

**Review by per1234 — APPROVED** [review]
It is working perfectly for me now.

Thanks for this very nice improvement to the user experience Akos!

**Pull request merged**
