### PR TITLE
Open Save as... dialog when saving sketches for the first time

### PR DESCRIPTION
**Pull request by federicobond**
Closes arduino/arduino-ide#64

This is my first contribution to arduino-ide, please let me know if anything is missing.

### CODE REVIEW

**Comment by ubidefeo** [comment]
hi @federicobond

This also fixes saving opened examples.
Thank you.

We'll do a code review and get back to you asap ✌️

**Review by per1234 — APPROVED** [review]
I tried it out and it works just as expected for me. Thanks @federicobond!

**Comment by 91volt** [comment]
@federicobond Thanks for your contribution! I was checking the behavior **when autosave is on** and you try to close a newly created or example sketch: it works as expected on `cmd/ctrl + w` or going to `file > close`, but I've noticed that **the dialog doesn't show when quitting the whole arduino IDE `cmd/ctrl + q` or closing the workspace from the  OS top bar's red quitting icon**. Would you be willing to address this one?

**Comment by federicobond** [comment]
@91volt I could not reproduce that. I'm seeing the _Are you sure you want to close this sketch?_ dialog in both cases, with Yes/No buttons.

**Comment by 91volt** [comment]
@federicobond Are you sure auto save is enabled? `File > Preferences > ☑ Auto save`

**Comment by federicobond** [comment]
@91volt interesting... I think it's a bit different problem, so if there aren't any other objections I would prefer to keep that fix out of the scope of this pull request.

I might take a look at it later.

**Comment by 91volt** [comment]
@federicobond thanks for checking it, I guess you are right, I'm gonna add a separate issue for that.

**Pull request merged**
