### PR TITLE
#1442 Link resolver for lib/boards manager

### LINKED ISSUE #1442: Are librarymanager and boardmanager links still clickable with IDE v2?
### Describe the problem

With IDE v1.8 Library Manager, we could include clickable links in examples which would open the library manager or board manager automatically.

With IDE v2, the only option seems to be to follow the link in a web browser, which then fails:

image

My question is: is there a new format for clickable library and board manager links in examples?

Thanks!
Paul

### To reproduce

Add a clickable link to an example and click it:

```
//Click here to get the library: http://librarymanager/All#SparkFun_u-blox_GNSS
```

### Expected behavior

The library manager used to open (with v1.8) - with v2 it does not... (Sad times!)

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
~**This PR depends on #1530**~ ✅ 

-----

### Motivation

To search in lib/boards manager from a particular URL.

In action:

https://user-images.githubusercontent.com/1405703/191589097-4dd4b82a-d95e-436b-80c1-a240f0289bf3.mp4

Test with:

```cpp
void setup() {}
void loop() {}
// Additional Board Manager URL:
// https://raw.githubusercontent.com/sparkfun/Arduino_Apollo3/main/package_sparkfun_apollo3_index.json
//
// http://boardsmanager/All#SparkFun_Apollo3
// ~http://boardsmanager/All#SparkFun%20Apollo3~ UNSUPPORTED. Use underscore (_) instead of `%20` (URL encoded space)
// http://librarymanager/All#SparkFun_u-blox_GNSS
// ~http://librarymanager/All#SparkFun%20u-blox%20GNSS~ UNSUPPORTED. Use underscore (_) instead of `%20` (URL encoded space)
// http://librarymanager/All/Display#SparkFun
// http://librarymanager/All/Sensors#SparkFun
// http://librarymanager/#SparkFun
// http://librarymanager/Updatable/Display#SparkFun
// http://librarymanager/All#SparkFun_u-blox_GNS
// http://boardsmanager#SAMD
// http://boardsmanager/Arduino%40Heart#littleBits
// http://librarymanager#WiFiNINA
// http://librarymanager/All#SparkFun_u-blox_GNSS
// http://librarymanager/All/Device%20Control#Servo
// http://librarymanager/All/Signal%20Input%2FOutput#debouncer
```

See the [specs](https://arduino.github.io/arduino-cli/dev/sketch-specification/#libraryboards-manager-links) and #1442 how it works.

### Other information

Closes #1442

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
@PaulZC could you please help us with the verification? Everything should work as in IDE 1.x (except for a few enhancements: https://github.com/arduino/arduino-cli/pull/1904#pullrequestreview-1129950882 and the topic support for libs). Please note the updated [example](https://github.com/arduino/arduino-ide/pull/1481#issue-1381376751); underscore `_` must be used in the hash, not `%20`. Let us know how it works for you. Thank you!

**Review by per1234 — APPROVED** [review]
It is working perfectly in all the provided test cases as well as for a sampling of URIs from the wild collected by searching my >2 GB mega-sketchbook.

Thanks Akos, both for adding the missing feature, and also for going above and beyond by actually making the "Type" filter work for the first time in the 6 year history of the feature, as well as adding "Topic" filter support!

**Comment by PaulZC** [comment]
Thank you @kittaakos @per1234 @cmaglie - it works perfectly for me.
Sincere best wishes,
Paul

**Review by francescospissu — APPROVED** [review]
Tested and it works as expected. Code changes and behavior approved.👍

**Pull request merged**
