### PR TITLE
Automatically remove editors for deleted files

### PR DESCRIPTION
**Pull request by msujew**
### Motivation

Closes https://github.com/arduino/arduino-ide/issues/648

### Change description

Listens to any changes of open editors and removes them if the `type` indicates that the underlying file has been deleted.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by AlbyIanna — APPROVED** [review]
LGTM

**Comment by AlbyIanna** [comment]
I think this might be related to #893. Probably solving it in that PR will make this one work properly too.

Let's wait for #893 to be merged before doing anything here.

**Comment by msujew** [comment]
@AlbyIanna You're right, I will address this issue in #893 probably 👍

**Comment by msujew** [comment]
@per1234 Since https://github.com/arduino/arduino-ide/pull/893 might take a while to get finished, I updated this PR to fix the issue you noticed. I found a clean solution. Please take another look :)

**Review by per1234 — APPROVED** [review]
The problem I reported in my previous review no longer occurs and it also solves https://github.com/arduino/arduino-ide/issues/648 as before.

Thanks @msujew!

**Review by AlbyIanna — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
