### PR TITLE
chore(deps): update to `theia@1.41.0`

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Use the latest Theia (`1.41.0`) dependencies in IDE2.

### Change description

 - Update the Theia dependencies from `1.39.0` to `1.41.0`.
 - Remove workaround for https://github.com/arduino/arduino-ide/pull/2144#pullrequestreview-1553632302 and https://github.com/eclipse-theia/theia/pull/12681.
 - Remove customized `async` behavior from the default workspace server service; it's available from Theia.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
I think the language pack extensions should be bumped to 1.80.0 per https://github.com/eclipse-theia/theia/commit/8f64a58e7eefca40718f5edc130cc63a5e8de52b

**Review by per1234 — CHANGES_REQUESTED** [review]
**UPDATE**: Fixed by https://github.com/arduino/arduino-ide/pull/2211/commits/c75d2b652c8e0210a0962929241a8b55dac5c533

<s>

## Unexpected introduction of "**New Text File**" menu item.

### To reproduce

1. Open the **File** menu.
  🐛 There is an unexpected "**New Text File**" menu item
1. Select "**New Text File**" from the menu.
  🐛 A new editor tab appears that is read-only and thus 

### Expected behavior

The **File** menu does not contain a "**New Text File**" menu item.

I think the established "**New Tab**" system available from the editor toolbar context menu is already sufficient for users to add additional files to their sketch so the added "**New Text File**" menu item would be superfluous even if it did function for adding files to the sketch.

### Arduino IDE version

9d02809 (tester build for https://github.com/arduino/arduino-ide/pull/2211/commits/2071ab827e6fa62906994836df839a9d5fa17552

### Operating system

Windows 11

### Additional context

I believe it was introduced by https://github.com/eclipse-theia/theia/commit/de2e7e1d2d249fe2925b1010a68f1b200d267eb4

</s>

**Review by per1234 — CHANGES_REQUESTED** [review]
## File path no longer shown in editor tab tooltip

Previously, the path of the file was shown in a tooltip (maybe the term for the content is "[label](https://theia-ide.org/docs/label_provider#:~:text=shown%20as%20a%20tooltip%20when%20you%20hover%20over%20the%20file%20in%20an%20opened%20editor%20tab)"?) when the mouse pointer was hovered over the editor tab.

Although not terribly valuable if you only consider the tabs of files from the sketch root, this feature was very useful when files from other locations were opened in the editor. This commonly occurs when using the "**Go to Definition**" feature, which might open editor tabs for files in obscure locations such as the platform core and platform bundled libraries.

### To reproduce

1. Select **File > Examples > 01.Basics > Blink** from the Arduino IDE menus.
1. Select **Tools > Board > Arduino AVR Boards > Arduino Uno** from the Arduino IDE menus.
1. Right click on the `pinMode` call in the editor.
1. Select "**Go to Definition**" from the context menu.
   A "**wiring_digital.c**" editor tab opens.
1. Hover the mouse pointer over the editor tab.

🐛 A tooltip showing the path of `wiring_digital.c` does not appear.

### Expected behavior

Tooltip showing path appears when an editor tab is hovered.

### Arduino IDE version

b86675f (tester build for https://github.com/arduino/arduino-ide/pull/2211/commits/c75d2b652c8e0210a0962929241a8b55dac5c533)

### Operating system

Windows 11

### Additional context

The fault does not occur when I use Arduino IDE 2.2.1:

image

The fault does not occur when I use [**Theia Blueprint**](https://theia-ide.org/docs/blueprint_download) version 1.41.0:

image

**Comment by kittaakos** [comment]
> ## File path no longer shown in editor tab tooltip
> Previously, the path of the file was shown in a tooltip (maybe the term for the content is "[label](https://theia-ide.org/docs/label_provider#:~:text=shown%20as%20a%20tooltip%20when%20you%20hover%20over%20the%20file%20in%20an%20opened%20editor%20tab)"?) when the mouse pointer was hovered over the editor tab.
> 
> Although not terribly valuable if you only consider the tabs of files from the sketch root, this feature was very useful when files from other locations were opened in the editor. This commonly occurs when using the "**Go to Definition**" feature, which might open editor tabs for files in obscure locations such as the platform core and platform bundled libraries.
> 
> ### To reproduce
> 1. Select **File > Examples > 01.Basics > Blink** from the Arduino IDE menus.
> 2. Select **Tools > Board > Arduino AVR Boards > Arduino Uno** from the Arduino IDE menus.
> 3. Right click on the `pinMode` call in the editor.
> 4. Select "**Go to Definition**" from the context menu.
>    A "**wiring_digital.c**" editor tab opens.
> 5. Hover the mouse pointer over the editor tab.
> 
> 🐛 A tooltip showing the path of `wiring_digital.c` does not appear.
> 
> ### Expected behavior
> Tooltip showing path appears when an editor tab is hovered.
> 
> ### Arduino IDE version
> [b86675f](https://github.com/arduino/arduino-ide/commit/b86675fa9f33ca6602ea9523619c05de6fcc10dd) (tester build for [c75d2b6](https://github.com/arduino/arduino-ide/commit/c75d2b652c8e0210a0962929241a8b55dac5c533))
> 
> ### Operating system
> Windows 11
> 
> ### Additional context
> The fault does not occur when I use Arduino IDE 2.2.1:
> 
> image
> 
> The fault does not occur when I use [**Theia Blueprint**](https://theia-ide.org/docs/blueprint_download) version 1.41.0:
> 
> image

Thank you! [d4b6a0d](https://github.com/arduino/arduino-ide/pull/2211/commits/d4b6a0de6ad4d019213443f3654accdcde60d1f7) should fix it.

**Review by per1234 — CHANGES_REQUESTED** [review]
**UPDATE:** Resolved by https://github.com/arduino/arduino-ide/pull/2211/commits/368ea63b43f9ab7d90e40208d6ec479871f61a7d

<s>

## Exception not printed to log when save fails

Arduino IDE is to save the sketch if the file attributes were. Previously an exception would be printed to the logs.

🐛 No indication or information about the failure is logged when saving fails due to the sketch having read-only file attributes.

### To reproduce

1. Set the read-only file attribute on a sketch.
1. Open the sketch in Arduino IDE.
1. Make a change to the sketch contents.
1. Select **File > Save** from the Arduino IDE menus.
   The dirty indicator remaining on the modified sketch file tab indicates the save attempt failed (failure is otherwise not indicated by the Arduino IDE UI: https://github.com/arduino/arduino-ide/issues/1501).

🐛 There is no indication or information about the failure in the logs.

### Expected behavior

Some useful information about the failure is logged when saving fails due to the sketch having read-only file attributes.

This is the exception logged by Arduino IDE 2.2.1:

```text
2023-09-15T06:47:06.522Z root ERROR Error: Unable to write file 'ReadOnly.ino' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'c:\Users\per\Documents\Arduino\ReadOnly\ReadOnly.ino')
    at x.asFileOperationError (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3656405)
    at x.rethrowAsFileOperationError (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3656337)
    at x.writeFile (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3654063)
    at async x.write (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3651260)
    at async d.doWrite (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3636421)
Caused by: Error: Request 'writeFile' failed
    at Proxy.<anonymous> (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3031719)
    at b.writeFile (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3740783)
    at x.doWriteUnbufferedQueued (file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3666184)
    at file:///C:/arduino-tools/221-2.2.1/resources/app/lib/frontend/bundle.js:2:3665870
Caused by: NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'c:\Users\per\Documents\Arduino\ReadOnly\ReadOnly.ino'
    at u (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1324559)
    at T.toFileSystemProviderError (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1348461)
    at T.open (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1341857)
    at async T.writeFile (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1341341)
    at async g.onRequest (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1083037)
    at async c.handleRequest (C:\arduino-tools\221-2.2.1\resources\app\lib\backend\main.js:2:1073930)
```

### Arduino IDE version

7a157e4 (tester build for https://github.com/arduino/arduino-ide/pull/2211/commits/d4b6a0de6ad4d019213443f3654accdcde60d1f7)

### Operating system

Windows 11

### Additional context

I do still see a logged exception when saving fails due to there being a [share access file write lock](https://en.wikipedia.org/wiki/File_locking) on the sketch.

</s>

**Comment by kittaakos** [comment]
> ### Expected behavior
> Some useful information about the failure is logged when saving fails due to the sketch having read-only file attributes.

Fixed in [368ea63](https://github.com/arduino/arduino-ide/pull/2211/commits/368ea63b43f9ab7d90e40208d6ec479871f61a7d). This will close #1501.


https://github.com/arduino/arduino-ide/assets/1405703/7f3d19ee-39ec-44e9-b9e3-722856d7c1ec

**Review by per1234 — APPROVED** [review]
Thanks Akos!

**Pull request merged**
