### PR TITLE
#1380 #1381 #1387 Improved the scrolling UX in list widgets

### LINKED ISSUE #1380: Scrollbar does not reach end of Library Manager list
### Describe the problem

With a total of over 5000 libraries available, the Arduino IDE Library Manager view often contains a long list of libraries now that all results are shown (https://github.com/arduino/arduino-ide/pull/1361).

The user may scroll through the list of results using the scrollbar on the right side of the view.

🐛 The end of the list can't be reached using the scrollbar when there are many search results.

### To reproduce

1. Open the "**Library Manager**" view.
1. Clear the "**Filter your search...**" field.
1. Click and drag the scrollbar to the bottom.

🐛 The list was not scrolled anywhere near to the end. You can use the mouse wheel to scroll down to verify there are many other listings.

### Expected behavior

Scrollbar can always be used to reach the end of the listings.

### Arduino IDE version

2.0.0-rc9.2.snapshot-0d545be

### Operating system

Windows

### Operating system version

10

### Additional context

I used the unfiltered list in the demo because it provides the most dramatic results, but it will also occur with filtered searches that provide a lot of results, such as `motor`.

image

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1381: Scrollbar trails increasingly behind mouse pointer position while scrolling Library Manager
### Describe the problem

The Arduino IDE Library Manager view displays a list of libraries matching the user's search query. Due to the large total number of libraries, the list will often be much longer than can fit in the vertical dimensions of the view, in which case the user may scroll through the list of results using the scrollbar on the right side of the view.

🐛 The scrollbar trails increasingly behind mouse pointer position while scrolling.

### To reproduce

1. Open the "**Library Manager**" view.
1. Type `servo` in the "**Filter your search...**" field.
   **ⓘ** This is only an arbitrary example of a common search query that might return enough results to require scrolling.
1. Click and drag the scrollbar downwards.

🐛 The position of the scrollbar trails increasingly behind the mouse pointer position. If the Arduino IDE window is near the bottom of the screen, it may even become necessary to stop and "grab" the bar once more in order to move it all the way to the bottom position.

image

### Expected behavior

Scrollbar position always matches mouse pointer position.

### Arduino IDE version

2.0.0-rc9.2.snapshot-0d545be

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

The issue was introduced in https://github.com/arduino/arduino-ide/pull/1361

---

Related: https://github.com/arduino/arduino-ide/issues/1380

### LINKED ISSUE #1387: Install interface of last item in Library/Boards Manager may not be accessible
### Describe the problem

The IDE's **Library Manager** and **Boards Manager** list the libraries and boards platforms that are available.

Since there are >5000 libraries, and even the primary package index alone contains a significant number of boards platforms, the length of the list will often exceed the vertical display area of the view, meaning the user will scroll down to reach items lower on the list.

When the mouse pointer is hovered over one of the list items, a version menu and "**INSTALL**" button are added at the bottom of the item.

🐛 The interface elements are not accessible for the last item on the list when the list height is equal to or greater than the vertical dimensions of the view.

### To reproduce

1. Open the **Library Manager** view in the Arduino IDE.
1. Type `servo` in the "**Filter your search...**" field.
   **ⓘ** This is only an arbitrary example of a list that exceeds the height of the view.
1. Scroll to the bottom of the list.
1. Hover the mouse pointer over the last item on the list
   🐛 The version menu and "**INSTALL**" button are not accessible.
1. Use the mouse wheel to scroll the list down farther.
   🐛 The list does not scroll down farther.

image

### Expected behavior

The installation interface is accessible on all **Library Manager** and **Boards Manager** items.

### Arduino IDE version

2.0.0-rc9.2.snapshot-20cc34c

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

I bisected the introduction to 5cb9166c839e7b7be19502bf28b45852127e84e4 (does not occur with the build for https://github.com/arduino/arduino-ide/commit/7828cc11ac172fdc8d62450ce8fc499d40d50aa1)

---

Even prior to the regression, the scrollbar didn't scroll the list down far enough for the interface to be visible on hover. However, previously you could use the mouse wheel to scroll it farther to reach the interface.

---

After the changes made in https://github.com/arduino/arduino-ide/pull/1385 to fix other scrolling-related issues, I find that it is sometimes possible to reach the interface, but not reliably:

last1

---

Related:

- https://github.com/arduino/arduino-ide/issues/1380
- https://github.com/arduino/arduino-ide/issues/1381

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Improves the scrolling in the library/boards manager widgets.

### Other information
Closes #1380
Closes #1381
Closes #1387

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — APPROVED** [review]
This fixes https://github.com/arduino/arduino-ide/issues/1380 for me.

I find that an offset between the mouse pointer position and the scrollbar position does still accumulate as reported in https://github.com/arduino/arduino-ide/issues/1381, but the magnitude is significantly less, so it doesn't harm the usability so much. In some cases, I find it now pushes the scrollbar **ahead** of the pointer instead of behind.

Thanks Akos!

**Comment by kittaakos** [comment]
Thank you for the review.

I want to work on this and cover #1387 if possible. I have also noticed the defect (see: [`ede7479`](https://github.com/arduino/arduino-ide/pull/1385/commits/ede74796bf7217bbec6b4b63194a4a049dc19847)), but the change was incorrect.

**Comment by kittaakos** [comment]
Per, could you please take another look? I think the UX is better now, and the changes should cover #1387. Thank you!

**Review by per1234 — CHANGES_REQUESTED** [review]
### Describe the problem

When the mouse pointer is hovered over one of the Library/Boards Manager or list items, a version menu and "**INSTALL**" button are added at the bottom of the item, which increases its vertical size.

🐛 When the length of the listings fits within the vertical dimension of the view when not hovered, but does not fit when hovered, some glitches occur.

### To reproduce

1. Open the "**Library Manager**" view.
1. Type `arduinoiotcloud` in the "**Filter your search...**" field.
   **ⓘ** This is only an arbitrary example of a search that produces a suitable length of listings. By chance it has the perfect length for the default window and view dimensions on my machine.
1. Resize the vertical dimension of the Arduino IDE window so that it is just long enough to show the full listings while in the non-hovered state, without a scrollbar on the Library Manager view.
   image
1. Hover the mouse pointer over "**Arduino_ConnectionHandler**".
   🐛 Only half the "**INSTALL**" button is shown:
   image
1. Hover the mouse pointer over "**ArduinoIoTCloud**".
   🐛 The "**INSTALL**" button is not shown:
   image
1. Hover the mouse pointer over "**ArduinoIoTCloudBearSSL**".
1. Move the mouse pointer horizontally until it is over the scrollbar (as would be a common user action after they see they need to scroll down to reach the version menu and buttons).
   🐛 The "**Library Manager**" view flickers rapidly between two states:
   flicker
   The flicker rate in real life is actually far higher than shown in the screencast GIF (the software was not able to capture it properly).

### Arduino IDE version

2.0.0-rc9.2.snapshot-f869314 (tester build for https://github.com/arduino/arduino-ide/pull/1385/commits/fe69093cf27b092bad8879b9d765b6ca27e6b085).

### Operating system

Windows 10

### Additional context

The issue also occurs with the previous build from this PR (though the flicker rate is lower): https://github.com/arduino/arduino-ide/commit/0694c2487dc30a4b1ff7077d92f9b9873341d44a.

The issue does not occur with the latest build from the `main` branch: https://github.com/arduino/arduino-ide/commit/20cc34ca9d9cde15f128b1213faa7f25d92ce83c

**Comment by kittaakos** [comment]
Thank you for the steps. I could reproduce the glitches and fix them locally. Could you please try again with the latest build? Thank you!

**Review by per1234 — APPROVED** [review]
I verified this resolves https://github.com/arduino/arduino-ide/issues/1380, https://github.com/arduino/arduino-ide/issues/1381, and https://github.com/arduino/arduino-ide/issues/1387.

The "flicker" bug I reported in [my previous review](https://github.com/arduino/arduino-ide/pull/1385#pullrequestreview-1095587897) is fixed. The issue with the buttons reported in that review is mitigated, though not 100% fixed, but it is not a serious defect and so I don't see that it is cause to delay the valuable advancements already provided by this PR. I will submit a separate report to track the remaining component (UPDATE, here: https://github.com/arduino/arduino-ide/issues/1403).

Thanks Akos!

**Pull request merged**
