### PR TITLE
Better tooltips.

### PR DESCRIPTION
**Pull request by dankeboy36**
Better tooltips.

https://user-images.githubusercontent.com/111981763/192629607-879de343-178e-4496-96c9-d5f2c8f8613d.mp4

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by Edivad99** [comment]
Nice, but I would fix having 2 identical pieces of information when holding Command. I would combine the last and penultimate lines since they report the same information

**Comment by kittaakos** [comment]
@Edivad99, if you are referring to [this:](https://github.com/arduino/arduino-ide/issues/1503#issuecomment-1259361269)

> * The fourth rectangle is a duplication of the information I have in the third rectangle

Then you misunderstood the feature. In the [monaco editor](https://github.com/microsoft/monaco-editor), if you press <kbd>Ctrl/⌘</kbd> while hovering over a symbol in the editor (see [`textDocument/docuemtnSymbol`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol)), `monaco` will show the actual code as a preview.

From the VS Code [docs](https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition):

> If you press Ctrl and hover over a symbol, a preview of the declaration will appear:

I do not think we will spend time removing an available feature, but I am positive there is a preference to disable it if required.

Here is an `.ino` file you can copy paste and try out locally:

```cpp
void setup() {
  sum(1, 2);
}
void loop() {}

/**
 * This is an example doc.
 *
 * @param left your number
 * @param right another number
 * @returns the sum of the args
 */
int sum(int left, int right) {
  int i = 0;
  // some comment
  int j = i;
  return left + right;
}
```

In action:

https://user-images.githubusercontent.com/1405703/192731197-2c71801b-87bd-4f36-b3a0-c63a5a42fd4f.mp4

Here is another example. It's coming from `Arduino.h`:

https://user-images.githubusercontent.com/1405703/192735693-51fc97f6-161d-4841-aca6-a204943f66eb.mp4

For completeness, people are [complaining](https://github.com/arduino/arduino-ide/issues/21#issuecomment-1090418999) about too slow and fast popups. It's possible to adjust it via the [advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings).

To disable the popup, add the following to the `settings.json` file:

```json
{
  "editor.hover.enabled": false
}
```

If you want to tune the popup delay, add this to the settings file:

```json
{
  "editor.hover.delay": 300
}
```

The default value is `300`, the minimum allowed value is `0`, and the maximum is `10000` in milliseconds.

In action:

https://user-images.githubusercontent.com/1405703/192737442-8fc0fb6d-cfe9-4c28-a37c-5b80b11124ea.mp4

**Comment by Edivad99** [comment]
I don't want to delete the feature, but it can be set that when I press command the penultimate rectangle disappears and only the last one remains visible

**Comment by kittaakos** [comment]
> but it can be set that when I press command the penultimate rectangle disappears and only the last one remains visible so you don't have 2 lines showing the method signature

If you want to tune how your editor works locally, you might find the corresponding settings [here](https://code.visualstudio.com/docs/getstarted/settings#_default-settings) to achieve it. Let us know how it went. Or maybe you can even open a PR with your proposed default settings.

**Comment by per1234** [comment]
>If you want to tune the popup delay, add this to the settings file:

To save any interested parties from confusion, I'll add that this setting is not working correctly: https://github.com/arduino/arduino-ide/issues/571

**Comment by per1234** [comment]
Thanks so much for your pull request and also for pointing out this error in the CLA text @dankeboy36!

@alranel can you make the suggested correction to [the CLA text](https://cla-assistant.io/arduino/arduino-ide)?

**Comment by alranel** [comment]
I'm unable to do it - the CLA is owned by the GitHub ArduinoBot user. Who has access to it? This is the gist to edit:
https://gist.github.com/ArduinoBot/69c5b68e989a47174b83b2bad2f4ecbf

**Review by kittaakos — COMMENTED** [review]
Works for me but I do not know why we need this additional styling. Maybe it's a Theia problem. If others are also OK, we can merge the PR.

@AlbyIanna, could you please also take a look? Thank you!

**Comment by per1234** [comment]
>Maybe it's a Theia problem.

Theia Blueprint 1.30.0 +  clangd extension has the same formatting problems as the Arduino IDE hover:

image

VS Code + clangd extension has the problem with the signature line, but not with the return type line:

image

**Comment by dankeboy36** [comment]
OK

Screen Shot 2022-10-06 at 20 53 54

**Review by AlbyIanna — APPROVED** [review]
I tested it and it works for me. Thank you @dankeboy36 !

If @per1234 is good with the changes too, I would merge this.

**Review by per1234 — APPROVED** [review]
It looks great. Thanks @dankeboy36!

**Pull request merged**
