### PR TITLE
#1016, #1274 Aligned the "Save your sketch" dialog behavior

### LINKED ISSUE #660: Remove **File > Close Editor** menu item
## Describe the current behavior

A new menu item **File > Close Editor** was introduced recently. This closes the currently selected editor.

The code files in the root of an Arduino sketch are always opened in the Arduino IDE editors. It is very rare for users to have any other editors open in the IDE. **File > Close Editor** has no effect when a sketch tab is selected. Its purpose is not clear from the title since we have never used the term "editor" to refer to an individual tab (we call them "tabs"). When a non-sketch file is open in an editor, the **X** on the right side of its tab will be the obvious method for closing it (with an alternative of using the "**View: Close Tab in Main Area**" keyboard shortcut).

My opinion is that this **File > Close Editor** will only cause confusion and add unnecessary complexity to the Arduino IDE's primary UI. I suspect that its introduction was unplanned.

## To reproduce

1. Select **File > Close Editor** from the Arduino IDE menus

Note that it doesn't do anything.

## Describe the request

Evaluate the need for **File > Close Editor**. If it doesn't offer anything of value to the users, remove it.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc1-snapshot.f0d9894
Date: 2021-11-30T16:25:41.414Z
CLI Version: 0.20.1 [abb21449]

### LINKED ISSUE #994: Save as native file dialog pops when enabling auto-save on a temp sketch
### Describe the problem

When I disable the auto-save, then enable it in a temp sketch, then the native save as file dialog pops. I think it should not.

A temp sketch is a sketch that is not saved to `directories#user` location.

### To reproduce

- Open a new sketch but do not touch it!
- Open settings and make sure auto-save is disabled.
- Enter one space to the end of the file.
- Open settings and enable auto-save.
- Hit OK.
- Native file dialog pops.

### Expected behavior

It should not. IDE2 should know it's a temp sketch and should not prompt the save as dialog.

Problem: by default, Theia saves the editor when this setting/preference is changed, and the new auto-save value "is enabled".

### Arduino IDE version

Version: 2.0.0-rc6-nightly-20220519 Date: 2022-05-19T03:30:29.656Z CLI Version: 0.21.0 [10107d24]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.3.1 (21E258)

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1016: Inconsistent dialogs when exit would result in user data loss
### Describe the problem

Under either of the following conditions, closing the Arduino IDE window would result in loss of sketch content:

- New or example sketch staged in a temporary folder
- Unsaved changes (user has disabled "**Auto save**")

As is standard for any application, the Arduino IDE notifies the user of this situation when they initiate a window close operation.

🐛 The presented dialogs are significantly different depending on which combination of the above conditions are present:

| Saved | New | "will not be saved" dialog | "Save your sketch" dialog |
| ----- | --- | -------------------------- | ------------------------- |
| Y     | Y   | N                          | Y                         |
| N     | Y   | Y                          | Y                         |
| N     | N   | Y                          | N                         |

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Check the box next to "**☐ Auto save**".
1. Click the <kbd>**OK**</kbd> button.
1. Select **File > New** from the Arduino IDE menus.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙂 Dialog offering save is presented:
   image
1. Click the <kbd>**Cancel**</kbd> button.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Uncheck the box next to "**`☑` Auto save**".
1. Click the <kbd>**OK**</kbd> button.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙁 Unintuitive and unhelpful "**Any unsaved changes will not be saved**" dialog appears:
   image
1. Click the <kbd>**Yes**</kbd> button.
   😕 Dialog offering save is presented.
1. Click the <kbd>**Cancel**</kbd> button.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch to any location and name you like.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙁 Unintuitive and unhelpful "will not be saved" dialog appears.
1. Click the <kbd>**Yes**</kbd> button.
   🐛 Standard dialog offering save is **not** presented.

### Expected behavior

Always show only the "Save your sketch" dialog.

Eradicate the unintuitive (https://github.com/arduino/arduino-ide/issues/677) and unhelpful (https://github.com/arduino/arduino-ide/issues/170) "**Any unsaved changes will not be saved**" dialog from the IDE.

### Arduino IDE version

2.0.0-rc6-snapshot-5b486b1

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [x] My report contains all necessary details

### LINKED ISSUE #1026: Example files - ask to save even if no changes were made to them.
### Describe the problem

If I open up an example sketch like blink and simply use it to program the board, and then try to close it without making 
any changes, unlike Arduino 1.x it asks me if I wish to save the sketch or not.  

This is related to #893,
which I am glad was fixed, but I do think it should only ask if the user made changes to the sketch.

There are other related example sketch issues, but I am pretty sure they have been reported in the past including:

1) Show sketch folder shows the folder within the temp directory, which feels wrong. 
2) Still looks like the examples don't show up in recent sketch list

3) If the temporary folder is erased, like you have the blink window open, go away for awhile and Norton Desktop cleans up the temp directory and erases your sketch,  you end up with a strange looking windows:
image
Note: I also saw some message in the window saying something like it can no longer track file changes... As there are too many... or some such thing (sorry should have taken picture then)

### To reproduce

Go to examples: file->Examples->01 Basic -> Blink

then after the window opens, click on the close button and you will see the dialog asking if you wish to save. 

The strange window issue, happens of Norton does a cleanup... Or you can emulate by opening the folder and delete all of the files out of that folder. 

### Expected behavior

Expect to only be asked to save a file if the file has been changed.

### Arduino IDE version

Nightly build 20220608

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

Sorry if I missed a duplicate. 

Also 2nd part not sure what to report... I know with Arduino 1.x when the temp is cleared, a compile will fail but the window still shows the file contents from before. 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1034: [UI] The dirty/close decorator is broken in IDE2
### Describe the problem

The dirty/close decorator does not look good when I hover over

### To reproduce

 - Create a new sketch,
 - Disable auto-save,
 - Click on the _Debug_ icon on the left,
 - Click on _Start Debugging_ (the play button),
 - Editor opens and it's dirty, and
 - Hover over the close icon.

https://user-images.githubusercontent.com/1405703/173062428-a6a9e944-ca11-475e-98d2-5cf42e8319a1.mp4

### Expected behavior

The `X` is visible when hovering over the dirty decorator.

### Arduino IDE version

Version: 2.0.0-rc7 Date: 2022-06-09T08:19:19.877Z CLI Version: 0.23.0 [899dc91b]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1274: Save dialog when closing app without changing sketches
### Describe the problem

The save dialog comes up when closing the app even when there are no changes in the sketch.

### To reproduce

Open the app, then close immediately without any changes to the sketches.

### Expected behavior

The save dialog on closing app should only appear when sketch are edited. 

### Arduino IDE version

Version: 2.0.0-rc9-nightly-20220802 Date: 2022-08-02T03:47:07.580Z CLI Version: 0.25.1 [436f0bb9]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.5

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Other information

Closes #1016
Closes #1274
Closes #1026
Closes #660
Closes #1034
Closes #994

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by ubidefeo** [comment]
@kittaakos 
I have found that when launching this build the automatically opened sketch is the first one listed in my Sketchbook.
The last one I had opened was an example (which I did not save, of course).
In case no previously open sketch is available to open again, it should do as IDE 1.x does: open a new Sketch

**Comment by kittaakos** [comment]
> this build the automatically opened sketch is the first one listed in my Sketchbook.
> In case no previously open sketch is available

@ubidefeo, but there is a sketch to open 👆 , the first one from the Sketchbook. If you delete `~/.arduinoIDE/recent-sketches.json` and `~/.arduinoIDE/recentworkspace.json`, the IDE2 should open a new temp sketch.

**Review by per1234 — CHANGES_REQUESTED** [review]
### Describe the problem

Sketch tab becomes closable after rename.

### To reproduce

1. Click the **●●●** icon on the right side of the editor toolbar.
1. Select "**New Tab**" from the menu.
1. In the "**Name for new file**" field, type `foo`
1. Click the <kbd>**OK**</kbd> button.
   🙂 The "**foo.ino**" tab does not have an **X** icon.
1. Click the **●●●** icon on the right side of the editor toolbar.
1. Select "**Rename**" from the menu.
1. In the "**New name for file**" field, type `bar.ino`
   🐛 The "**bar.ino**" tab has an **X** icon.

image

### Arduino IDE version

2.0.0-rc9.2.snapshot-948a6ed (tester build for [948a6ed](https://github.com/arduino/arduino-ide/commit/9a2d13feeeeca92d94b6e84bbbc2270b7a64272d))

### Operating system

Windows 10

**Comment by kittaakos** [comment]
> The last one I had opened was an example (which I did not save, of course).
> In case no previously open sketch is available to open again, it should do as IDE 1.x does: open a new Sketch

I have tried it, and the IDE (1.x) opens the example. Steps to reproduce:
 - Open IDE (1.x),
 - Open an example (I picked the `File` > `Examples` > `01. Basic` > `AnalogReadSerial`),
 - Close all sketches if you have any,
 - Quit the IDE (1.x),
 - Open the IDE (1.x),
 - You have the `AnalogReadSerial` sketch opened.

The IDE2 never behaved like this 👆 .

**Review by per1234 — APPROVED** [review]
### Describe the problem

Regression of https://github.com/arduino/arduino-ide/issues/831

Closability of tabs for files in the `src` subfolder was lost.

### To reproduce

1. Put this "**HasSrcFolder**" sketch to your sketchbook: [HasSrcFolder.zip](https://github.com/arduino/arduino-ide/files/8056883/HasSrcFolder.zip)
1. Open the "**HasSrcFolder**" sketch in the Arduino IDE.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Check the box next to "**☐ Show files inside Sketches**".
1. Click the <kbd>**OK**</kbd> button.
1. Open the "**Sketchbook**" view.
1. Click on **HasSrcFolder/src/InSrcFolder.cpp**
   🐛 There is no **X** icon on the **InSrcFolder.cpp** tab.

image

### Expected behavior

Tabs for files in the `src` subfolder are closable, as is the behavior of the IDE build from the `main` branch:

image

### Arduino IDE version

2.0.0-rc9.2.snapshot-948a6ed (tester build for 948a6ed)

### Operating system

Windows 10

### Additional context

See https://github.com/arduino/arduino-ide/issues/831 for details on why closability of these files specifically is needed.

See https://github.com/arduino/arduino-ide/pull/946 for the original code change that enabled this closability.

**Comment by per1234** [comment]
>IDE 1.x still allows you to have the app open without any workspaces.

Is this behavior specific to macOS @ubidefeo? https://github.com/arduino/arduino-ide/pull/487

**Comment by kittaakos** [comment]
> 7\. In the "**New name for file**" field, type `bar.ino`
>     🐛 The "**bar.ino**" tab has an **X** icon.


> Closability of tabs for files in the `src` subfolder was lost.


Thank you for the steps, Per. Both issues should be fixed now.

**Review by per1234 — APPROVED** [review]
I verified that it fixes all targeted issues:

- https://github.com/arduino/arduino-ide/issues/1034
- https://github.com/arduino/arduino-ide/issues/1016
- https://github.com/arduino/arduino-ide/issues/994
- https://github.com/arduino/arduino-ide/issues/660
- https://github.com/arduino/arduino-ide/issues/1274 / https://github.com/arduino/arduino-ide/issues/1026

As well as the two problems I reported via my previous reviews:

- https://github.com/arduino/arduino-ide/pull/1351#pullrequestreview-1086666656
- https://github.com/arduino/arduino-ide/pull/1351#pullrequestreview-1086669300

**Review by davegarthsimpson — APPROVED** [review]

**Pull request merged**
