### PR TITLE
chore(deps): update to Theia `1.42.1`

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Use the latest Theia version: `1.42.1`.

### Change description
 - Update VS Code translation versions to `1.81.0` (where available)
 - Disable eclipse-theia/theia#12867

### Other information

IDE2 will automatically get the multi-line search feature from Theia (eclipse-theia/theia#12868):

https://github.com/arduino/arduino-ide/assets/1405703/d3073b0c-fd8f-4add-b5d1-80c2c76076b7

I do not expect any other Theia behavioral changes, but here is the diff: https://github.com/eclipse-theia/theia/compare/v1.41.0...v1.42.1. I disabled one undesired new feature (eclipse-theia/theia#12867) from Theia.

### Reviewer checklist

- [ ] PR addresses a single concern.
- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
- [ ] PR title and description are properly filled.
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
## Internationalization lost for some menu items

### To reproduce

1. Select **File > Preferences** from the Arduino IDE menus.
1. Select a language other than English from the "**Language**" menu.
1. Open the \<edit\> menu.
   (where \<edit\> is the localized name for the peek menu item)
   🐛 The following menu items are not localized:
   - Undo
   - Redo
   - Cut
   - Copy
   - Paste
   - Select All
1. Right click on the editor view.
   🐛 The following menu items are not localized:
   - Redo
   - Undo
   - Cut
   - Copy
   - Paste

### Expected behavior

All strings exposed in the Arduino IDE UI are internationalized

### Arduino IDE version

133ff30 (tester build for 46632076e952dc9c76d05e11b515834dcbfb8d2e)

### Operating system

Windows 11

### Additional context

The fault is not present when using the latest build from the `main` branch (69b7365)

---

Maybe caused by https://github.com/eclipse-theia/theia/pull/12951

---

Related: https://github.com/arduino/arduino-ide/issues/2213

---

Since we seem to experience this type of regression regularly (made more likely since breaking changes are made to the API of the VS Code language pack without making a major version bump as would be required for semver-compliance), it would be very useful to find a way for the CI system to catch it.

The Theia code knows when there is no localization data for an i18n key (which should always indicate a bug):

https://github.com/eclipse-theia/theia/blob/v1.42.1/packages/core/src/common/i18n/localization.ts#L53-L54

but it doesn't make that information available.

**Comment by kittaakos** [comment]
> find a way for the CI system to catch it.

OK. Let's find an automated solution for this problem.

**Review by per1234 — CHANGES_REQUESTED** [review]
## Compile operations can't be triggered

### Describe the problem

Triggering any of the following operations has no effect:

- Verify/Compile
- Upload
- Upload Using Programmer
- Export Compiled Binary

### To reproduce

1. Select any board from the **Tools > Board** menu.
1. Select **Sketch > Verify/Compile** from the Arduino IDE menus.

🐛 There is no reaction.

### Expected behavior

All strings exposed in the Arduino IDE UI are internationalized

### Arduino IDE version

133ff30 (tester build for 46632076e952dc9c76d05e11b515834dcbfb8d2e)

### Operating system

Windows 11

### Additional context

The fault is not present when using the latest build from the `main` branch (69b7365)

---

Triggering the fault doesn't cause any log output to be produced.

---

The fault occurs regardless of how the operation is triggered:

- Via the menu items
- Via the toolbar buttons
- Via the command palette

---

Other operations such as **Tools > Burn Bootloader**, Library Manager installation, Boards Manager installation do work as expected.

**Comment by kittaakos** [comment]
We should use https://github.com/eclipse-theia/theia/releases/tag/v1.43.0 instead.

**Comment by kittaakos** [comment]
It's obsolete. The next target is [1.46.1](https://github.com/eclipse-theia/theia/releases/tag/v1.46.1)

**Comment by kittaakos** [comment]
https://github.com/arduino/arduino-ide/pull/2362

**Pull request closed without merging**
