### PR TITLE
Dialog focus

### LINKED ISSUE #1373: User fields dialog improvements
### Describe the request

When the dialog opens, the focus is not on the first `<input>` just as in other places:
 - new file dialog,
 - open one of the list widgets,
 - etc.

It helps users to continue the work without clicking here and there.

Also, please change `Configure And Upload` to `Configure and Upload`.

Pipe dream: add a description to the dialog of what it does.

https://user-images.githubusercontent.com/1405703/187457367-1ff93467-80ec-4aa8-80d5-1ea2d8e2eac8.mp4

### Describe the current behavior

See the issue description.

### Arduino IDE version

34a7fdb

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
Some dialogs, when being opened, don't set the focus on the controls (inputs, button, etc)

### Change description
Fixed the focus in the following dialogs:
- Configure and Upload
- Firmware Uploader
- Certificate Uploader

Also changed "Configure And Upload" label to "Configure and Upload".

### Other information
Fixes #1373 

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by kittaakos — CHANGES_REQUESTED** [review]
It's not working for me. When I try to upload the dialog opens but the `<input>` does not have the focus.


https://user-images.githubusercontent.com/1405703/191441265-5fd18032-683c-487a-83c6-b82d1378adf0.mp4

**Comment by AlbyIanna** [comment]
@kittaakos Thank you for spotting it. Please try it again, it should work correctly now.

**Review by kittaakos — CHANGES_REQUESTED** [review]
It does not work for me. Once the focus is removed, IDE2 does not put back the focus back to the `<input>` on dialog open.


https://user-images.githubusercontent.com/1405703/192236835-f6e4fd5b-f7d9-450b-85c4-6b8b45eeeec3.mp4

I have not checked the button focus changes yet.

**Comment by AlbyIanna** [comment]
> It does not work for me. Once the focus is removed, IDE2 does not put back the focus back to the <input> on dialog open.

You're right, it works only the first time. I've fixed it now, thanks for spotting it!

**Review by kittaakos — APPROVED** [review]
Setting the focus on the `<input>` field works great in the user field dialog. Thank you!

I have noticed this difference between 2.0.0 and build from this PR. The first button has a bold border for the firmware updater and the SSL certificate dialogs.

`2.0.0`:
Screen Shot 2022-09-29 at 13 27 22

Build from PR:
Screen Shot 2022-09-29 at 13 27 32

`2.0.0`:
Screen Shot 2022-09-29 at 13 27 47

Build from PR:
Screen Shot 2022-09-29 at 13 28 05


#1373 is not mentioning this change, If this is what we want, please proceed with the merge.

**Comment by AlbyIanna** [comment]
@kittaakos those borders are bold because the focus goes on them when the dialog shows up. #1373 only mentions the user fields dialog, but I wanted to solve the issue more broadly. Thanks for the review!

**Comment by kittaakos** [comment]
> but I wanted to solve the issue more broadly.

Can you explain why did you decide to set the focus on the buttons only in these two dialogs and not on the others?

**Comment by AlbyIanna** [comment]
> Can you explain why did you decide to set the focus on the buttons only in these two dialogs and not on the others?

My reasoning was to try to set the focus on the _most appropriate_ UI element in the dialog. Of course, the definition of _most appropriate_ is arbitrary, so I did what I thought it was best.

Here's the reasoning I've applied on each dialog:
- the user fields one needs to have the focus on the first input element because when the user opens it, the will need to fill them in in order to upload
- with the firmware updater one, the first action the user would like to take is to press the button (if a board is found) because a board is automatically selected
- when the user opens the SSL root certificate one, it's usually not possible to click on the **UPLOAD** button because if you don't add a certificate before it will be disabled, so I've set the focus on the first button

So, generally I guess my rationale was to set the focus on the UI element that lets the user do what they want to do with a dialog _as quickly as possible_.

Of course, all of this is questionable, so if you have suggestions or if you disagree with these decisions, please let me know!

**Comment by kittaakos** [comment]
> So, generally I guess my rationale was to set the focus on the UI element that lets the user do what they want to do with a dialog _as quickly as possible_.

Thank you for writing down the explanation.

**Pull request merged**
