### PR TITLE
fix: menu item enablement issues

### LINKED ISSUE #1533: IDE2 is misusing Placeholder menu items for the disabled menus
### Describe the request

Every non-separator and non-group menu item in Theia is backed by a command. The menu item's enablement is defined by the handler of the command associated with the menu item. (See [here](https://github.com/eclipse-theia/theia/blob/fb11a223d0da1ac591189c6a21eeb87c17fd102f/packages/core/src/common/command.ts#L123)). But, in Theia, there is no dynamic menu in the electron app (See [here](https://github.com/eclipse-theia/theia/issues/446)), so no matter if `isEnabled` `false`, the menu item will always be enabled. (See [here](https://github.com/eclipse-theia/theia/blob/fb11a223d0da1ac591189c6a21eeb87c17fd102f/packages/core/src/electron-browser/menu/electron-main-menu-factory.ts#L183))

The placeholder menu items were created only for IDE2 to allow adding additional "label" menus. Such as the followings:
Screen Shot 2022-10-05 at 16 28 05
Screen Shot 2022-10-05 at 16 28 18

The placeholder menu items are permanently disabled, as they're not backed by a command.

IDE2 started to misuse the placeholder label for disabled menu items. It's incorrect. To prove, make sure one of the following menu items are disabled and note that the keybinding is missing from the menu item:
Screen Shot 2022-10-05 at 16 28 34
Screen Shot 2022-10-05 at 16 28 40

Instead of using the placeholder solution and manually rebuilding the entire menu on disablement changes, IDE2 should customize the electron main menu factory, must not set the menu item enablement to `true`, rely on the `isEnabled` function of the handler, and update the electron menu with the `MenuManager`.

### Describe the current behavior

See the description. The expected bahevior is that the associated keybinding is visible for the menu even if the menu item itself is disabled

### Arduino IDE version

61a11a08

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### LINKED ISSUE #1722: "Sketch > Upload" menu item disabled after upload w/ Serial Monitor open
### Describe the problem

Under certain conditions, the **Sketch > Upload** and **Sketch > Upload Using Programmer** menu items are disabled after the completion of an upload:

- Upload is made to a native USB CDC serial port
- Serial Monitor is open

#### Equipment

Any Arduino board that uses a native USB CDC serial port for uploads.

Examples:

- Leonardo
- Micro
- MKR Boards
- Nano 33 IoT
- Nano 33 BLE
- Teensy (only when uploading to the board's port from the "Serial ports" section of the **Tools > Port** menu)

#### Steps

1. Select **File > New Sketch** from the Arduino IDE menus.
1. Connect the Arduino board to your computer.
1. Select the board and port in Arduino IDE.
1. Open the **Serial Monitor** view if it is not already open.
1. Select **Sketch > Upload** from the Arduino IDE menus.
   **ⓘ** The fault also occurs if the upload operation is triggered by clicking the "Upload" button or using the <kbd>**Ctrl**</kbd>+<kbd>**U**</kbd> keyboard shortcut.
1. Wait for the upload to finish successfully.
1. Open the **Sketch** menu.

🐛 The **Sketch > Upload** and **Sketch > Upload Using Programmer** menu items are disabled for no good reason:

image

### Expected behavior

The **Sketch > Upload** and **Sketch > Upload Using Programmer** menu items are only disabled if uploading is impossible. The only conditions under which that would be the case is when no board is selected (and programmer in the case of **Upload Using Programmer**). However, the **Sketch > Upload** and **Sketch > Upload Using Programmer** menu items are even enabled in this case (which is reasonable since it allows the IDE to communicate the requirement of selecting a board and programmer to the user).

### Arduino IDE version

d6a4b0f

### Operating system

Windows

### Operating system version

10

### Additional context

The fault first occurs for me with https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc (does not occur when using the build for https://github.com/arduino/arduino-ide/commit/6984c52b927260e13e23ae6eeb6f0b7488f7e12d)

---

I have not been able to reproduce the fault on Linux and the reports have been from Windows users.

---

I found that the number of platforms installed affects my ability to reproduce the fault. With my full collection of ~40 platforms, I find that the fault only occurs when using https://github.com/arduino/arduino-ide/commit/ac9cce16f749f7b43abc145ed8d1ee79159dd5e9 or newer, and that I am unable to reproduce the fault when uploading to a Teensy board even then. So if you are having difficulty reproducing the fault, try a minimal data directory that only contains the single platform of the board you are uploading to.

---

The upload operation can still be triggered via the Upload button or <kbd>**Ctrl**</kbd>+<kbd>**U**</kbd> keyboard shortcut even after the **Sketch > Upload** menu item was disabled.

---

The **Sketch > Upload** and **Sketch > Upload Using Programmer** menu items are re-enabled after selecting a different board or port.

---

The fault does not occur when uploading to boards without a native USB CDC serial port:

- Uno
- Mega
- Nano Every

---

Originally reported at https://forum.arduino.cc/t/ide-2-0-2-forgets-how-to-upload/1054971/1

Additional reports:

- https://forum.pjrc.com/threads/71525-Problem-when-uploading-program-to-T4-1-in-IDE-2-0-2?p=316071&viewfull=1#post316071
- https://forum.pjrc.com/threads/71525-Problem-when-uploading-program-to-T4-1-in-IDE-2-0-2?p=316404&viewfull=1#post316404
- https://forum.arduino.cc/t/ide-2-0-2-forgets-how-to-upload/1054971/5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Fixes the `Sketch` > `Upload`/`Upload Using Programmer` menu items enablement. This PR is related to arduino/arduino-ide#1735 and covers arduino/arduino-ide#1533.

---- 

IDE2 switched from always-enabled menu items to dynamic ones with [this](https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc#diff-2635a822041da8b5a20323e233457da36a84db3817c6bd3ba9e7e944fefca04aR155-R157) change and [here](https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc#diff-2635a822041da8b5a20323e233457da36a84db3817c6bd3ba9e7e944fefca04aR245) is the crucial part.

Without rebuilding the entire menu, there is no way to support a dynamic menu in an electron app. So in Theia, the menu is calculated at startup, and all menu items are always enabled even though the underlying commands could be disabled. The menu remains the same for the app session—no need to rebuild anything, but the command enablement can change at runtime. If a menu is enabled and the underlying command is disabled, nothing happens when the user clicks on the menu item. This is the vanilla Theia behavior.

IDE2 heavily relies on dynamic menus. IDE2 has to recalculate the menu on board attach/detach, selection change, library/platform installation uninstallation, etc., events. A dynamic menu with the correct menu items enablement state is something IDE2 could provide without much additional effort if it were done correctly. See arduino/arduino-ide#1533.

This PR cleans up the placeholder menu items, makes the menu items rely on the command enablement state, and "manually" updates the menus when needed. 

### Change description

The following logic was changed:
 - `Edit` > `Increase Font Size`/`Decrease Font Size` (no behavior change is expected),
 - `Tools` > `Upload SSL Root Certificates` (disabled when the dialog is opened),
 - `Tools` > `WiFi101 / WiFiNINA Firmware Updater` (disabled when the dialog is opened),
 - `Sketch` > `Verify/Compile` (disabled when verifying),
 - `Sketch` > `Export Compiled Binary` (disabled when verifying),
 - `Sketch` > `Upload` (disabled when uploading),
 - `Sketch` > `Configure and Upload` (disabled when uploading), and
 - `Sketch` > `Upload Using Programmer` (disabled when uploading)

Other expected behavior changes (my PR is a proposal, I am happy to adjust if required)
 - When `Sketch` > `Verify/Compile` is disabled, `Sketch` > `Export Compiled Binary` is also disabled and vice versa.
 - When `Sketch` > `Upload` is disabled, `Sketch` > `Upload Using Programmer` is also disabled and vice versa. The same is true for `Sketch` > `Configure and Upload`.
 - When an upload is running, for the (automatic) verify part, the `Sketch` > `Verify/Compile` and `Sketch` > `Export Compiled Binary` are disabled.
 - When the upload is running, but the (automatic) compilation part has already passed, the `Sketch` > `Verify/Compile` and `Sketch` > `Export Compiled Binary` menu items are enabled, but the `Sketch` > `Upload`, `Sketch` > `Upload Using Programmer`, and `Sketch` > `Configure and Upload` menu items are still disabled until the end of the upload command.

Finally, this PR eliminates the following warning on macOS, maybe on other OSs too. Can be reproduced when starting the IDE2 from a terminal, and the `window` receives a `blur` and then `focus` event. (Lose focus from IDE2 app, set focus to IDE2 app):

```
DEBUG Skipping menu item with missing command: "workbench.action.files.newUntitledFile".
```

This PR has no intention changing anything regarding the command/menu enablement in the toolbar.

### Other information

Closes arduino/arduino-ide#1533
Closes arduino/arduino-ide#1722

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
I noticed this PR causes a change in the behavior of the buttons. I think the new behavior is reasonable, but it was not mentioned in the PR description so I thought it was worth mentioning in case it was unintended/unwanted.

I seem to remember we discussed the idea of having this behavior some time ago and it was rejected, but I might be misremembering and I don't have a strong preference for either behavior.

## Behavior of IDE from `main`

When the user triggers an "Upload" operation in any of the builds from the `main` branch, the "Upload" button, and only that button, is given the active coloration during the entire course of the operation (which includes both a compile and an upload phase):

main

## Behavior of IDE from PR

When the user triggers an "Upload" operation using the build from this PR, in addition to the "Upload" button having the active coloration during the entire course of the operation, the "Compile" button is given the active coloration during the compile phase of the "Upload" operation:

pr

**Comment by kittaakos** [comment]
Great that you have mentioned it. I did not plan to change it. We can restore what we have on the `main`, but we can continue with this "new feature" if it adds value.

> I seem to remember we discussed the idea of having this behavior some time ago and it was rejected, but I might be misremembering and I don't have a strong preference for either behavior.

Yes. The thread is starting here: https://github.com/arduino/arduino-ide/pull/1260#pullrequestreview-1055723635

Let me know how to proceed. Thank you!

**Review by per1234 — CHANGES_REQUESTED** [review]
@kittaakos I've been giving it some more thought and I think the behavior of the button coloration in the builds from `main` is better. I think it is good to give the user some feedback about the progress thought the phases of the "Upload" operation to the user (as is already done to some extent via the notifications), but I don't think button coloration is the right way to do that. If I click a button, I don't expect another button to show an activation state.

**Comment by kittaakos** [comment]
I have restored the toolbar behavior. Now, it should be the same as on the `main`. The menu item disablement is still expected to work as described in https://github.com/arduino/arduino-ide/pull/1750#issue-1484632964. Please review. Thank you!

**Review by per1234 — APPROVED** [review]
I verified that:

- https://github.com/arduino/arduino-ide/issues/1722 is fixed
- Added menu item disabling when allowing user access would be inappropriate is working as specified.
- Verify button behavior on Upload is the same as the builds from `main`

Thanks Akos!

**Pull request merged**
