### PR TITLE
ATL-1137: Show error when could not connect to CLI

### PR DESCRIPTION
**Pull request by kittaakos**
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by kittaakos** [comment]
@per1234, @rsora, what should we do with this PR? Thank you!

**Comment by per1234** [comment]
I think it's a very important improvement. I have tried it out myself and also have interacted with a couple users who were able to use it to troubleshoot problems.

**Review by per1234 — APPROVED** [review]
I have already encountered several situations where the information provided by this change is essential for troubleshooting.

Library installed with invalid metadata, now displays the helpful error message:
```
Request loadSketch failed with message: 2 UNKNOWN: cannot initialize package manager: libraries rescan: loading libs from c:\Users\per\Documents\Arduino\libraries: loading library from c:\Users\per\Documents\Arduino\libraries\BadLib: loading library.properties: Error reading file: Error parsing data at line 0: Invalid line format, should be 'key=value'
```

Platform installled under an invalid version folder name, now displays the helpful error message:
```
Request loadSketch failed with message: 2 UNKNOWN: cannot initialize package manager: error loading hardware packages: loading hardware from c:\Users\per\AppData\Local\Arduino15\packages: loading package arduino: invalid version dir C:\Users\per\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.foo: no patch version found
```

No access to the Internet on first startup, now displays the helpful error message:
```
Request loadSketch failed with message: 2 UNKNOWN: downloading builtin:ctags@5.8-arduino11 tool: Get "https://downloads.arduino.cc/tools/ctags-5.8-arduino11-pm-i686-mingw32.zip": dial tcp: lookup downloads.arduino.cc: no such host
```

Use of a proxy server (the IDE currently requires the user to configure the proxy settings in the preferences), now displays the helpful error message:
```
Request loadSketch failed with message: 2 UNKNOWN: downloading builtin:ctags@5.8-arduino11 tool: Get "https://downloads.arduino.cc/tools/ctags-5.8-arduino11-pm-i686-mingw32.zip": dial tcp 104.18.28.45:443: connectex: No connection could be made because the target machine actively refused it.
```

Previously, all these diverse issues only resulted in the IDE hanging at the splash screen and a generic `root ERROR Could not create client for gRPC.` error message if you ran it from the command line.

**Comment by kittaakos** [comment]
Thank you for the review. 👍

**Pull request merged**
