### PR TITLE
Fixed sorting of sketches and examples - ignore case

### PR DESCRIPTION
**Pull request by Sebastian-Brzuzek**
simple solution for issue #185

### CODE REVIEW

**Comment by kittaakos** [comment]
Thanks for your contribution, @Sebastian-Brzuzek. Your PR currently depends on #213. Please bear with us.
The fix seems good to me. Can we do the same for libraries? We have to change the code here:
https://github.com/arduino/arduino-ide/blob/5c8669d699b5f02251d04f338ea9b87999786893/arduino-ide-extension/src/browser/contributions/include-library.ts#L117

**Comment by Sebastian-Brzuzek** [comment]
@kittaakos thanks for feedback. It looks like there is general problem with Action Menu in Theia. Take a look at this commit: https://github.com/Sebastian-Brzuzek/theia/commit/c06060722e957560bc9f4ed992fc98e1a20d2b57 

I can see the following options:

1. Convince Theia team to make global change - which will solve this kind of problems once for all.
2. Find all references where registerMenuAction method is used in Arduino Ide and to add precalculated `order` property as needed.
3. Add some kind of "wrapper" to `registerMenuAction` method (or `MenuAction`) to override current Theia implementation in one place for Arduino Ide project.

I can help with option 2 or 3. But I'm not sure if I will have time to make some progress with option 1.

One more question - what is expected order in case of menu items with labels which differ only on lower/upper case letter level? I know it is a little bit strange edge case 😉 

Maybe there are some other options, what do you think?

**Comment by kittaakos** [comment]
For the sake of simplicity, I am going to approve this PR once you have rebased it from the `main`. Could you please do that? 😊 After the rebase, the workflow should restart and pass. #213 was merged.

Thank you so much for looking into the possible solutions.

> 1. Convince Theia team to make global change - which will solve this kind of problems once for all.

Let's do this. I can help with this.

> 2\. Find all references where registerMenuAction method is used in Arduino Ide and to add precalculated `order` property as needed.

We could do that, but once we have a Theia-based solution, it's unnecessary.

> 3\. Add some kind of "wrapper" to `registerMenuAction` method (or `MenuAction`) to override current Theia implementation in one place for Arduino Ide project.

Ideally, it should be possible to customize the default `MenuModelRegistry` in Theia. I will look into this as part of the first option.

**Comment by Sebastian-Brzuzek** [comment]
It has taken some time (I have done rabase using the GitHub Desktop App for the first time :smiley: ) but finally checks are successful ;-)

Regarding customization of the default `MenuModelRegistry` in Theia, it is great idea for flexible solution, which will allow for safe transition without breaking changes.

**Comment by kittaakos** [comment]
> It has taken some time (I have done rabase using the GitHub Desktop App for the first time 😃 ) but finally checks are successful.

I am glad you've managed to do it 💪 

I have checked your code, it looks good to me. I also tried your changes in-action, it's also good.

Screen Shot 2021-03-17 at 09 29 13

We need approval from someone else. @ubidefeo could you please verify the change and approve it if you like it? Thank you!

**Review by kittaakos — APPROVED** [review]
Thank you for your contribution, @Sebastian-Brzuzek 👍 Your changes look good to me.

**Review by ubidefeo — APPROVED** [review]
thank you for your contribution @Sebastian-Brzuzek 
sorry it took me a while to chime in with my 👍🏼  

🙏🏼

**Pull request merged**
