### PR TITLE
fix: relaxed condition to check if resource exists

### LINKED ISSUE #1586: "Built-in" examples fail to open
### Describe the problem

The Arduino IDE installation includes a collection of "built-in" example sketches that demonstrate fundamental sketch concepts. These are accessed via the "**01.Basics**" section of the **File -> Examples** menu.

These "built-in" example sketches fail to open.

The following is shown in the log:

```
root ERROR Request cloneExample failed with error: Sketch does not exist: [object Object]
```

I have verified that they do exist.

I have also reset the IDE (and all related folders) to see if that fixes it, it doesn't.

### To reproduce

1. Select **File -> Examples -> 01.Basics > Blink** from the Arduino IDE menus.

🐛 Nothing at all happens. The "Blink" sketch does not open. No error message is shown in the IDE UI.

### Expected behavior

New window should open with example.

### Arduino IDE version

2.0.1

### Operating system

Linux

### Operating system version

- Arch Linux

### Additional context

The bug does not occur when opening library example sketches or normal sketches.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

To open built-in examples from an AppImage.

### Change description

Relaxed the condition to check if a resource exists.
The original (`fs-extra`-based) implementation did not check if the file is writable either.
Resources are not writable in mounted AppImages.

### Other information

Closes #1586

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
> I was never able to reproduce #1586 with the Linux ZIP package,

Me neither, but I thought it was an app image issue. Has anybody had the same issue with the ZIP?

> so I can't verify it fixes the reported problem as it applies to that package. I do suspect that the cause was the same (e.g., perhaps there is a way to run the IDE from inside the ZIP package without extracting the archive?), and therefore will also be fixed by this PR.

I learned this the hard way. If the app image is started, the [`AppDir` is mounted read-only](https://docs.appimage.org/introduction/software-overview.html#apprun). If you start the ZIP image, the contained resources (such as the built-ins) are resolved with the absolute FS path instead of the mounted one. From [here](https://github.com/arduino/arduino-ide/issues/1586#issuecomment-1302278490):

> root INFO cloneExample file:///tmp/.mount_arduin6hMpJz/resources/app/node_modules/arduino-ide-extension/Examples/01.Basics/AnalogReadSerial

VS

> root INFO cloneExample file:///home/parallels/Desktop/dev/arduino-ide/electron/build/dist/linux-unpacked/resources/app/node_modules/arduino-ide-extension/Examples/01.Basics/AnalogReadSerial

Since it was read-only, the `exists` logic gave a false negative result, so the built-in sketch creations failed with the sketch does not exist error when IDE2 was started as an app image.

**Comment by per1234** [comment]
>Has anybody had the same issue with the ZIP?

Yes, the original reporter:

https://github.com/arduino/arduino-ide/issues/1586#issuecomment-1297815416

> @per1234 you changed my report to add the line:
>
>>The bug does not occur when using the ZIP package of the IDE.
>
>but this is incorrect. ALL of my testing was done with the zip package. I never tested with the appimage

**Comment by kittaakos** [comment]
OP of #1586 has confirmed that it worked with the ZIP. So only the AppImage was affected. I am removing the `on hold` label.

**Review by AlbyIanna — APPROVED** [review]
Neat! Code is 👍

**Pull request merged**
