### PR TITLE
Update Theia to 1.22.1

### PR DESCRIPTION
**Pull request by msujew**
The largest change in the update to Electron 15 is that `remote` is now exported from `@electron/remote` instead of `electron` directly.

Please check whether the electron related functionality still works as expected. The application runs correctly on my machine with Electron 15.

Regarding the change in the readme: Theia 1.20 shipped with a fix for the `rebuild` issue, so it can be run from the root of the repo again.

### CODE REVIEW

**Comment by fstasi** [comment]
@msujew I updated the CI updating node to 14, but there's an issue with `dugite-extra` which is used by `@theia/git@1.22.1` and is locked to v12. 

I guess we can open a PR [here](https://github.com/theia-ide/dugite-extra) and update to node 14

```
error dugite-extra@0.1.14: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <13". Got "14.18.2"
```

**Review by per1234 — DISMISSED** [review]
Thanks for updating [the ARM build documentation](https://github.com/arduino/arduino-ide/blob/msujew/theia-update-1.22/docs/internal/Arm.md) @fstasi!

I see two other places in the documentation where Node.js 12 is still specified:

## `docs/internal/Ubuntu.md`

https://github.com/arduino/arduino-ide/blob/msujew/theia-update-1.22/docs/internal/Ubuntu.md

```
&& nvm install 12.14.1 \
&& nvm use 12.14.1 \
&& nvm alias default 12.14.1 \
```

## `BUILDING.md`

https://github.com/arduino/arduino-ide/blob/msujew/theia-update-1.22/BUILDING.md#build-from-source

> Please refer to the [Theia IDE prerequisites](https://github.com/theia-ide/theia/blob/master/doc/) documentation for the setup instructions.

https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

> - Node.js `>= 12.14.1`.
>   - For now, use Node 12.

I wonder if it would be best to specify the prerequisites directly in this repository's documentation?

The current approach of pointing to the Theia docs at the tip of the `master` branch is a bad idea because that documentation is not guaranteed to be correct for the version of Theia used in this project. The alternative would be to use the ref for the version that is in use. In this case it would be:
https://github.com/eclipse-theia/theia/blob/v1.22.1/doc/Developing.md#prerequisites
and then remember to update the link at each bump. But that still assumes that those docs will always be correct for Arduino IDE.

**Comment by fstasi** [comment]
@per1234 Thanks for pointing me out the `Ubuntu.md` file, I did miss it!

Regarding the link to the Theia building instructions, I'm not sure if it would be better to integrate such extensive doc in our codebase and maintain it and where to place it so that it's available for ppl with issues building but not "too much" visible when developers just want to jump in a contribute. What is your take on that?

**Comment by fstasi** [comment]
@msujew we also noticed this error that breaks the menus (and potentially other stuff)

```
root ERROR ReferenceError: Electron is not defined
    at ElectronMainMenuFactory.createOSXMenu (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_lib_electron-browser_theia_core_electron-menu-module_js.bundle.js:361:47)
    at ElectronMainMenuFactory.createElectronMenuBar (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_lib_electron-browser_theia_core_electron-menu-module_js.bundle.js:314:35)
    at ElectronMenuContribution.setMenu (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/vendors-node_modules_theia_core_lib_electron-browser_menu_electron-menu-contribution_js.bundle.js:992:46)
    at ElectronMenuContribution.update (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_lib_electron-browser_theia_core_electron-menu-module_js.bundle.js:424:14)
    at refreshMenu (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_node_modules_moment_locale_sync_recursive_-arduino-ide-extension_lib_br-8d6f5c.bundle.js:6437:34)
    at file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_node_modules_moment_locale_sync_recursive_-arduino-ide-extension_lib_br-8d6f5c.bundle.js:6439:75
    at file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/bundle.js:56828:69
    at CallbackList.invoke (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/bundle.js:56834:26)
    at Emitter.fire (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/bundle.js:56946:29)
    at NotificationCenter.notifyRecentSketchesChanged (file:///Users/francesco/projects/arduino/arduino-ide/electron-app/lib/arduino-ide-extension_node_modules_moment_locale_sync_recursive_-arduino-ide-extension_lib_br-8d6f5c.bundle.js:11455:43)
```

**Comment by per1234** [comment]
>such extensive doc

Unless I misunderstand, it is really not much content.

This is the entirety of it:

> ## Prerequisites
> 
>  - Node.js `>= 12.14.1`.
>    - For now, **use** Node 12.
>    - Node 14 is supported, Node 16 _should_ work, but you might need to run `yarn --ignore-engines` to get around some arbitrary > constraints.
>    - If you are interested in Theia's VS Code Extension support then you should use a Node version at least compatible with the one > included in the version of Electron used by [VS Code](https://github.com/microsoft/vscode).
>  - [Yarn package manager](https://yarnpkg.com/en/docs/install)  `>= 1.7.0` **AND** `< 2.x.x`.
>  - git (If you would like to use the Git-extension too, you will need to have git version 2.11.0 or higher.)
> 
> Some additional tools and libraries are needed depending on your platform:
> 
> - Linux
>   - [make](https://www.gnu.org/software/make/)
>   - [gcc](https://gcc.gnu.org/) (or another compiling toolchain)
>   - [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/)
>   - build-essential: `sudo apt-get install build-essential`
>   <a name="prerequisite_native_keymap"></a>
>   - [`native-keymap`](#prerequisite_native_keymap) native node module dependencies:
>     - Debian-based: `sudo apt-get install libx11-dev libxkbfile-dev`
>     - Red Hat-based: `sudo yum install libX11-devel.x86_64 libxkbfile-devel.x86_64 # or .i686`
>     - FreeBSD: `sudo pkg install libX11`
>   <a name="prerequisite_keytar"></a>
>   - [`keytar`](#prerequisite_keytar) native node module dependencies ([reference](https://github.com/atom/node-keytar#on-linux)):
>     - Debian/Ubuntu: `sudo apt-get install libsecret-1-dev`
>     - Red Hat-based: `sudo yum install libsecret-devel`
>     - Arch Linux: `sudo pacman -S libsecret`
>     - Alpine: `apk add libsecret-dev`
> 
> - Linux/MacOS
>   - [nvm](https://github.com/nvm-sh/nvm) is recommended to easily switch between Node.js versions.
> 
> - Windows
>   - We recommend using [`scoop`](https://scoop.sh/). The detailed steps are [here](#building-on-windows).

---

>and maintain it

Yeah, this would be the motivation for the current approach of referencing the Theia docs. We avoid the need to maintain a copy of that information here.

>What is your take on that?

It depends on this question: "Is the Theia documentation accurate for the Arduino IDE project?"

If the answer is "yes", then we should continue to reference it, but we should pin to the specific version that is accurate.

If the answer is "no", then we should maintain our own build dependencies installation instructions.

Since the Theia docs say Node.js 12, it seems to me that they are not accurate for Arduino IDE.

**Comment by msujew** [comment]
@fstasi This is still work in progress, I'm currently trying to fix the build error in the MacOS CI. Given that you were able to run the electron build, did you not experience the build error?

**Comment by fstasi** [comment]
> @fstasi This is still work in progress, I'm currently trying to fix the build error in the MacOS CI. Given that you were able to run the electron build, did you not experience the build error?

@msujew I confirm I was able to build and run the IDE on my intel mac laptop :). The build is succesful and the application starts, with the above run time error.

As a side note, the build itselft also works on the CI, my understanding is that the packaging of the electron executable is not working

**Comment by per1234** [comment]
Instructions for dependencies installation are essential to building, so I think the appropriate place for them is in the `BUILDING.md` document.

The information currently under the "Architecture overview" and "FAQ" is far less essential, and so would be reasonable to move to separate files that are linked to from `BUILDING.md`, or even from a `CONTRIBUTING.md` file when it comes to things not directly relevant to building.

**Comment by fstasi** [comment]
@msujew thanks for the progress on this one!

There is still some issue with the packaged version of the application: I get this error running the executable on mac:
```
/Applications/Arduino\ IDE.app/Contents/MacOS/Arduino\ IDE
Starting backend process. PID: 27246
/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Module did not self-register: '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/drivelist/build/Release/drivelist.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at bindings (/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/drivelist/js/index.js:25:27) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by msujew** [comment]
@fstasi Yep, I noticed that one as well. I wanted to see whether simply disabling the `npmRebuild` would fix the issue, but it seems like they don't get build at all in that case...

Anyway, I talked with Paul about that, and he way quite confused as well, given that we don't rebuild `oniguruma` (the source of the rebuild issue) at all in the Theia repo. I'll investigate this further, but it's tricky ;)

**Comment by msujew** [comment]
@fstasi Would you mind testing the newest artifacts on MacOS? I believe it builds and runs correctly now.

**Comment by fstasi** [comment]
> @fstasi Would you mind testing the newest artifacts on MacOS? I believe it builds and runs correctly now.

@msujew I confirm it does start! The solution is quite clever btw!

**Comment by silvanocerza** [comment]
I still get the same error on the M1. What am I missing? 

```
~/workspace/arduino-ide on  remotes/origin/msujew/theia-update-1.22
$ yarn
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error dugite-extra@0.1.14: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <13". Got "14.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by silvanocerza** [comment]
Nevermind, I forgot to add `--ignore-engines` when calling `yarn`. 🤦 

Nonetheless it still fails, seems like there are no native `grpc-tools` binaries? 

```
warning Error running install script for optional dependency: "/Users/alien/workspace/arduino-ide/node_modules/grpc-tools: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments:
Directory: /Users/alien/workspace/arduino-ide/node_modules/grpc-tools
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@14.19.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/alien/workspace/arduino-ide/node_modules/grpc-tools/bin/grpc_tools.node\" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.0/darwin-arm64.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.0/darwin-arm64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.0/darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/alien/workspace/arduino-ide/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:412:35)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/alien/workspace/arduino-ide/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:267:9)
node-pre-gyp ERR! System Darwin 21.3.0
node-pre-gyp ERR! command \"/Users/alien/.nvm/versions/node/v14.19.0/bin/node\" \"/Users/alien/workspace/arduino-ide/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd /Users/alien/workspace/arduino-ide/node_modules/grpc-tools
node-pre-gyp ERR! node -v v14.19.0
```

**Comment by msujew** [comment]
@silvanocerza Well, that's a complicated one...

So basically, it boils down to the `grpc-tools` package not being available for Apple M1 machines, due to not being able to run M1 builds on GitHub Actions, see [this](https://github.com/grpc/grpc-node/issues/1405#issuecomment-784609436) discussion. I believe this will also be an issue for this repo considering that the testing Artifacts for the IDE cannot be compiled for M1 on GH Actions.

I would try to get this PR merged regardless, since it's not a regression (I believe Theia didn't build on M1 before as well?) and not even really Theia related.

**Comment by silvanocerza** [comment]
That's a shame, does this also mean that developing the project on M1 is not feasible? 
Because if it's not I think it's gonna be a problem in the short term. As of now there's only me with an M1 in the team but I mostly use it for testing and other project since I have another Linux machine, but probably others in the team are gonna need an upgrade in the close future so that might become a problem.

**Comment by msujew** [comment]
Given what others have written in the [linked issue](https://github.com/grpc/grpc-node/issues/1405#issuecomment-1003652357), it should be possible to build the dependency yourself and instruct `node-pre-gyp` to use a different mirror for downloading the binary. The comment author links to a version of `grcp-tools` (1.11.2) running on M1 which is available at `https://github.com/maschwenk/grpc-node/raw/2dd28e1ab8211533007dd2df5ae632de60006983/artifacts/`. To use it, an env variable has to be set:

```bash
npm_config_grpc_tools_binary_host_mirror="https://github.com/maschwenk/grpc-node/raw/2dd28e1ab8211533007dd2df5ae632de60006983/artifacts/" yarn
```

It shouldn't be a showstopper for you to release the Arduino-IDE on M1, but makes it a bit more difficult.

**Comment by silvanocerza** [comment]
Good to know, thanks Mark!

**Comment by fstasi** [comment]
@msujew this PR looks good to me, anything pending before we can merge it?

**Review by fstasi — APPROVED** [review]

**Comment by msujew** [comment]
@fstasi This is ready to merge now :) I removed the `--ignore-engines` fields in favor of using yarn resolutions and everything seems to work as expected. Thanks for the continuous feedback!

**Pull request merged**
