### PR TITLE
#39 Avoid deleting the workspace when it's still in use

### LINKED ISSUE #39: Occasional "Unable to watch for file changes in this large workspace" warnings
I occasionally get this warning from a new, bare minimum sketch:
```
Unable to watch for file changes in this large workspace. Please follow the instructions link to resolve this issue.
```
Clipboard01

There doesn't seem to be any pattern to when I get it. I have a nearly empty sketchbook with only one library installed.

The linked instructions are certainly nothing a beginner would enjoy being exposed to:https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

It seems like this is a spurious warning and not a good user experience, especially for a beginner who won’t understand how to interpret it and may treat it as a “red herring” for completely unrelated problems they are having ([example](https://github.com/arduino/arduino-ide/issues/151)).

[ originally reported by @per1234 ]

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

To fix the _unable to watch file changes in this large workspace_ notification when saving a temp sketch.

### Change description

 - From now on, NSFW service disposes after removing the last reference. No more 10sec delay.
 - Moved the temp workspace deletion to a startup task.
 - Can set the initial task for the window from electron-main.
 - Removed the `browser-app`.

### Other information

Closes #39

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — APPROVED** [review]
Unfortunately I am not able to confirm the fix because, even though I have encountered https://github.com/arduino/arduino-ide/issues/39 periodically throughout the years of using this application, I never managed to figure out how to reproduce it.

What I have done is try various shenanigans involving workspaces and file watcher on both my Windows and Linux machines to try to break something and didn't manage to find any misbehavior that doesn't also occur with the build from the `main` branch.

So at least I can say that I didn't find any regressions.

Thanks for your work to eradicate this confusing error Akos!

**Comment by kittaakos** [comment]
> periodically throughout the years of using this application, I never managed to figure out how to reproduce it.

I can reproduce it on macOS with the following steps (same as [here](https://github.com/arduino/arduino-ide/issues/39#issuecomment-1043454719)):
 - have a sketch opened from your sketchbook in IDE2,
 - create a new sketch and save it with `Ctrl/Cmd+S` (it's crucial to *save* and not *save as*) without doing anything else,
 - see the error in the first window.

I hope this helps; I could consistently reproduce the issue with these steps 👆 Let me know how it went. Thank you!

**Comment by per1234** [comment]
Thanks! I am able to reproduce the bug by following the procedure you provided when using 2.0.0-rc9.4 on both Windows and Linux. When I do the same using the build from this PR, I am not able to reproduce the bug.

**Review by AlbyIanna — APPROVED** [review]
Code LGTM.

A minor remark I've got is that there are still mentions to `browser-app`
- https://github.com/arduino/arduino-ide/blob/5f82577bc19fa38a3f24fa27c1c2f6a01a977083/docs/internal/release-procedure.md?plain=1#L15
- https://github.com/kittaakos/arduino-ide/blob/1d3c98190ea58921fdb8ba16112107ef91f79268/.eslintrc.js#L20
- https://github.com/kittaakos/arduino-ide/blob/1d3c98190ea58921fdb8ba16112107ef91f79268/.eslintrc.js#L20
- https://github.com/kittaakos/arduino-ide/blob/%2339/package.json#L51
- https://github.com/kittaakos/arduino-ide/blob/%2339/electron/packager/index.js#L123

**Comment by kittaakos** [comment]
Thank you for the remarks. 👍 

> * https://github.com/kittaakos/arduino-ide/blob/1d3c98190ea58921fdb8ba16112107ef91f79268/.eslintrc.js#L20
> * https://github.com/kittaakos/arduino-ide/blob/1d3c98190ea58921fdb8ba16112107ef91f79268/.eslintrc.js#L20

I will take care of them. (By the way, they're the same.)

> * https://github.com/kittaakos/arduino-ide/blob/%2339/package.json#L51

I do not understand this feedback 👆 

> * https://github.com/kittaakos/arduino-ide/blob/%2339/electron/packager/index.js#L123

Do you want me to update the comment or remove the step?

**Comment by AlbyIanna** [comment]
> Do you want me to update the comment or remove the step?

I was just referring to the comment, but I see you already changed it.

Thank you!

**Comment by kittaakos** [comment]
> Thank you!

Thanks for reviewing it and finding the leftovers. Once the build is green, I merge the PR.

**Pull request merged**
