### PR TITLE
IDE startup theme based on OS theme

### LINKED ISSUE #530: Dark theme is used on clean start despite "Light (Arduino)" being the default
When the Arduino IDE is started from a clean system (no configuration files from a previous IDE run), it is using the dark theme even though the default preference setting is for the light theme.

### Steps to reproduce

1. Delete the IDE's configuration folders (e.g., `C:\Users\per\.arduinoIDE`, `C:\Users\per\AppData\Roaming\arduino-ide`, 
1. Start the IDE. Note that it is in dark mode
1. Open **File > Preferences**. Note that the theme is set to "Light (Arduino)".

### Expected behavior

The IDE uses the "Light (Arduino)" theme by default.

### Environment

Version: 2.0.0-beta.11-snapshot.da6b66f
Date: 2021-10-06T08:06:21.909Z
CLI Version: 0.19.1 alpha [718bbbf2]
OS: Windows 10

### Additional information

This does not occur when the same steps are followed with 2.0.0-beta.11

### PR DESCRIPTION
**Pull request by francescospissu**
### Motivation
The theme of the IDE on first launch should be the same as the OS.

### Change description
Implemented a patch that replaces the `ThemeService.get().loadUserTheme();` function at startup by directly setting the theme based on the OS theme.
For all subsequent starts of the IDE the theme applied will be the last one set by the user.

### Other information
With the current version of Theia adopted (1.25) it is not possible to extend the `ThemeService`, it will be possible starting from Theia 1.27.
Once the version of Theia is updated, this patch will be removed and this functionality will be implemented via dependency injection.

Closes #530.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
This should work: https://github.com/arduino/arduino-ide/compare/fspissu/startup-theme...kittaakos:arduino-ide:startup-theme-2
If you have any questions, let me know.

**Comment by francescospissu** [comment]
Thanks for your support @kittaakos. In a later step I can create a contribution on Theia to achieve this directly there.

**Review by kittaakos — APPROVED** [review]
Thank you! I did not check the behavior but the code changes look good to me.

----

Could you please ask the Theia community why we need this hack?

**Review by AlbyIanna — APPROVED** [review]
Nice hack 😎 

I tested it on MacOS and it works perfectly.

LGTM 🚀

**Pull request merged**
