### PR TITLE
Remove trailing colon when parsing the protocol from URL

### LINKED ISSUE #1775: "Preferences" dialog shows proxy is configured as SOCKS after user configures HTTP proxy
### Describe the problem

Users may access the Internet via a [proxy server](https://en.wikipedia.org/wiki/Proxy_server). Arduino IDE can be configured for this use case via the "**Network**" tab of the "**Preferences**" dialog.

Two types of proxies are supported:

- HTTP
- [SOCKS](https://en.wikipedia.org/wiki/Proxy_server#SOCKS_proxy)

The proxy type is selected via a radio button on the dialog.

🐛 The radio button is set to "**SOCKS**" after the IDE is reloaded even though the user selected the "**HTTP**" radio button in the "**Preferences**" dialog when they configured the proxy preferences.

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Click the "**Network**" tab.
1. Select the "**Manual proxy configuration**" radio button.
1. Configure proxy as follows:
   - Select the "**HTTP**" radio button.
   - Set "**Host name**" to `example.com`
   - Set "**Port number**" to `42`
   - Set "**Username**" to `foo`
   - Set "**Password**" to `bar`
1. Click the <kbd>**OK**</kbd> button.
   The index download process may now fail. This is expected due to the use of an dummy proxy configuration for the demo.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start Arduino IDE.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Click the "**Network**" tab.

🐛 The radio button is set to "**SOCKS**":

image

### Expected behavior

Proxy type radio button in the "**Preferences**" dialog always correctly reflects the proxy type that was configured.

### Arduino IDE version

908ec4c

### Operating system

Windows

### Operating system version

10

### Additional context

The "**Preferences**" dialog shows the correct "**HTTP**" radio button if the dialog is opened again after configuring the proxy but before restarting Arduino IDE. The fault only occurs after a restart.

---

The `network.proxy` key in `~/.arduinoIDE/arduino-cli.yaml` does have the `http` URL scheme as expected even though the "**Preferences**" dialog indicates it is a SOCKS proxy (for which Arduino IDE [currently uses the `socks` URL scheme](https://github.com/arduino/arduino-ide/issues/1769)):

```yaml
network:
  proxy: http://foo:bar@example.com:42/
```

---

Originally reported by @wh201906 at https://github.com/arduino/arduino-ide/issues/1769

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by wh201906**
### Motivation
This PR should fix #1775

### Change description
Remove the trailing colon when parsing the protocol in URL string

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by wh201906** [comment]
I tested it on Windows and #1775 is fixed as expected.
I used `Windows_X86-64_zip` in the build artifacts for test.
https://github.com/arduino/arduino-ide/actions/runs/3718811226

**Comment by wh201906** [comment]
I have little experience of typescript. If my code style in this PR is not good, please tell me how to improve it. Thanks.

**Comment by kittaakos** [comment]
The code changes look good to me. When I set and use the SOCKS scheme in the `Settings` > `Network` tab, I get the `socks://username:pwd@hostname:port` construct in the `arduino-cli.yaml` file.

I noticed the following, however:

Use these settings:

Screen Shot 2022-12-21 at 10 58 21

IDE2 will send the following config object to the CLI:

```json
{
  "board_manager": {
    "additional_urls": [
      "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
    ]
  },
  "daemon": {
    "port": "50051"
  },
  "directories": {
    "data": "/Users/a.kitta/Library/Arduino15",
    "user": "/Users/a.kitta/Documents/Arduino"
  },
  "library": {
    "enable_unsafe_install": false
  },
  "locale": "en",
  "logging": {
    "file": "",
    "format": "text",
    "level": "info"
  },
  "metrics": {
    "addr": ":9090",
    "enabled": true
  },
  "output": {
    "no_color": false
  },
  "sketch": {
    "always_export_binaries": false
  },
  "updater": {
    "enable_notification": true
  },
  "network": {
    "proxy": "http://username:pwd@alma:1234/"
  }
}
```

The updated CLI config will be this:

```yaml
board_manager:
  additional_urls:
  - https://arduino.esp8266.com/stable/package_esp8266com_index.json
daemon:
  port: "50051"
directories:
  builtin:
    libraries: /Users/a.kitta/Library/Arduino15/libraries
  data: /Users/a.kitta/Library/Arduino15
  downloads: /Users/a.kitta/Library/Arduino15/staging
  user: /Users/a.kitta/Documents/Arduino
library:
  enable_unsafe_install: false
locale: en
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
network:
  proxy: socks://username:pwd@my_hostname:3636
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
```

When I use the HTTP scheme in the `Settings` > `Network` tab:

Screen Shot 2022-12-21 at 11 04 18


The IDE2 will send the following config JSON to the CLI:

```json
{
  "board_manager": {
    "additional_urls": [
      "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
    ]
  },
  "daemon": {
    "port": "50051"
  },
  "directories": {
    "data": "/Users/a.kitta/Library/Arduino15",
    "user": "/Users/a.kitta/Documents/Arduino"
  },
  "library": {
    "enable_unsafe_install": false
  },
  "locale": "en",
  "logging": {
    "file": "",
    "format": "text",
    "level": "info"
  },
  "metrics": {
    "addr": ":9090",
    "enabled": true
  },
  "network": {
    "proxy": "http://u:p@host:2345/"
  },
  "output": {
    "no_color": false
  },
  "sketch": {
    "always_export_binaries": false
  },
  "updater": {
    "enable_notification": true
  }
}
```

But the CLI config YAML will be this:

```yaml
board_manager:
  additional_urls:
  - https://arduino.esp8266.com/stable/package_esp8266com_index.json
daemon:
  port: "50051"
directories:
  builtin:
    libraries: /Users/a.kitta/Library/Arduino15/libraries
  data: /Users/a.kitta/Library/Arduino15
  downloads: /Users/a.kitta/Library/Arduino15/staging
  user: /Users/a.kitta/Documents/Arduino
library:
  enable_unsafe_install: false
locale: en
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
network:
  proxy: http://u:p@host:2345/
  user_agent_ext: daemon
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
```

👆 Note the additional `network@user_agent_ext: daemon` entry. I could not consistently reproduce it.

----

I have also noticed when switching from either SOCK or HTTP proxy to no proxy config, the CLI config does not update correctly. The `network` prop remains in the YAML.

Have this `Settings` > `Network` tab:

Screen Shot 2022-12-21 at 11 09 53


IDE2 sends this CLI config JSON to CLI:

```json
{
  "board_manager": {
    "additional_urls": [
      "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
    ]
  },
  "daemon": {
    "port": "50051"
  },
  "directories": {
    "data": "/Users/a.kitta/Library/Arduino15",
    "user": "/Users/a.kitta/Documents/Arduino"
  },
  "library": {
    "enable_unsafe_install": false
  },
  "locale": "en",
  "logging": {
    "file": "",
    "format": "text",
    "level": "info"
  },
  "metrics": {
    "addr": ":9090",
    "enabled": true
  },
  "network": {},
  "output": {
    "no_color": false
  },
  "sketch": {
    "always_export_binaries": false
  },
  "updater": {
    "enable_notification": true
  }
}
```

But the CLI YAML will be this:
```yaml
board_manager:
  additional_urls:
  - https://arduino.esp8266.com/stable/package_esp8266com_index.json
daemon:
  port: "50051"
directories:
  builtin:
    libraries: /Users/a.kitta/Library/Arduino15/libraries
  data: /Users/a.kitta/Library/Arduino15
  downloads: /Users/a.kitta/Library/Arduino15/staging
  user: /Users/a.kitta/Documents/Arduino
library:
  enable_unsafe_install: false
locale: en
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
network:
  proxy: http://uname:korte@hostname:4567/
  user_agent_ext: daemon
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
```

The `network` prop must be missing or empty. It's probably a CLI bug, as IDE2 never writes the config file.

**Review by kittaakos — APPROVED** [review]
I have verified the changes and confirm that it fixes #1775. When I configure the `socks` protocol in the `Settings` > `Network` tab, I have the expected `socks://username:pwd@hostname:port` construct in the `~/.arduinoIDE/arduino-cli.yaml` file.

Thank you for the help!

**Comment by kittaakos** [comment]
> IDE2 will send the following config object to the CLI:

FYI: If one starts the IDE2 from the console, the actual CLI config JSON object is dumped when saving the `Settings` dialog and updating the CLI config through the daemon.

**Comment by wh201906** [comment]
I guess we need to start a new issue to resolve the problems you find in https://github.com/arduino/arduino-ide/pull/1778#issuecomment-1361115824?

**Comment by wh201906** [comment]
> FYI: If one starts the IDE2 from the console, the actual CLI config JSON object is dumped when saving the `Settings` dialog and updating the CLI config through the daemon.

It's helpful. Thanks.

**Comment by kittaakos** [comment]
> I guess we need to start a new issue to resolve the problems you find in [#1778 (comment)](https://github.com/arduino/arduino-ide/pull/1778#issuecomment-1361115824)?

Thanks for your prompt reaction. Yes, we will take care of the follow-ups, and it does not affect this PR. No action is required (unless you want to start working on the other bugs 😉, but they need to be confirmed first.)

**Comment by per1234** [comment]
> I have also noticed when switching from either SOCK or HTTP proxy to no proxy config, the CLI config does not update correctly. The network prop remains in the YAML.

This bug is tracked at https://github.com/arduino/arduino-cli/issues/1677

**Pull request merged**
